# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bowtiegui.ui'
#
# Created: Tue Mar  1 14:46:40 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 1500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 1500))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1500))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.centralWidget = QtGui.QWidget(MainWindow)
        layout = QtGui.QVBoxLayout(self.centralWidget)
        layout.addWidget(self.scrollArea)

        #self.scrollArea.setGeometry(QtCore.QRect(0, 0, 41, 111))
        #self.scrollArea.setWidgetResizable(True)
        #self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        #self.scrollAreaWidgetContents = QtGui.QWidget()
       # self.scrollArea.setGeometry(QtCore.QRect(230, 0, 841, 2481))
        self.scrollArea.setFrameShape(QtGui.QFrame.WinPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(7)
        self.scrollArea.setWidgetResizable(False)
       # self.scrollArea.setToolTip("place cursor over the controls for information")

        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 812,3052))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        layout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)

        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(50, 10, 741, 3000))
        self.frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
        self.frame.setObjectName(_fromUtf8("frame"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.selgtflbl = QtGui.QLabel(self.frame) # select gtf file
        self.selgtflbl.setGeometry(QtCore.QRect(10, 30, 291, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.selgtflbl.setFont(font)
        self.selgtflbl.setToolTip("select the GTF file produced by cufflinks")
        self.selgtflbl.setObjectName(_fromUtf8("selgtflbl"))

        self.selfile = QtGui.QPushButton(self.frame) # single gtf file
        self.selfile.setGeometry(QtCore.QRect(10, 50, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selfile.setFont(font)
        self.selfile.setToolTip("Click here to select single GTF file")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.selfile.setIcon(icon)
        self.selfile.setToolTip("click here to select the file")
        self.selfile.setObjectName(_fromUtf8("selfile"))

        self.mulfile = QtGui.QPushButton(self.frame)
        self.mulfile.setGeometry(QtCore.QRect(50, 50, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile.setIcon(icon)
        self.mulfile.setToolTip("Click here to select multiple GTF file")
        self.mulfile.setObjectName(_fromUtf8("mulfile"))

        self.builselcom = QtGui.QComboBox(self.frame)
        self.builselcom.setGeometry(QtCore.QRect(90, 50, 641, 27))
        self.builselcom.setToolTip("Please select the file")
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        #font.setBold(True)
        #font.setPointSize(11)
        #font.setBold(False)
        #font.setItalic(False)
        font.setWeight(50)
        self.builselcom.setFont(font)
        self.builselcom.setObjectName(_fromUtf8("builselcom"))


        self.omitlbl = QtGui.QLabel(self.frame) #Do you want to Omit Tabular Datasets
        self.omitlbl.setGeometry(QtCore.QRect(10, 100, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.omitlbl.setFont(font)
        self.omitlbl.setObjectName(_fromUtf8("omitlbl"))

        self.asno = QtGui.QPushButton(self.frame)
        self.asno.setGeometry(QtCore.QRect(60, 120, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)

        font.setWeight(50)
        self.asno.setFont(font)
        self.asno.setObjectName(_fromUtf8("asno"))

        self.asyes = QtGui.QPushButton(self.frame)
        self.asyes.setGeometry(QtCore.QRect(10, 120, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)

        font.setWeight(50)
        self.asyes.setFont(font)
        self.asyes.setObjectName(_fromUtf8("asyes"))


        self.sqlbl = QtGui.QLabel(self.frame) #Do you want to Generate SQLite
        self.sqlbl.setGeometry(QtCore.QRect(10, 170, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sqlbl.setFont(font)
        self.sqlbl.setObjectName(_fromUtf8("sqlbl"))

        self.asno1 = QtGui.QPushButton(self.frame)
        self.asno1.setGeometry(QtCore.QRect(60, 190, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.asno1.setFont(font)
        self.asno1.setObjectName(_fromUtf8("asno1"))

        self.asyes1 = QtGui.QPushButton(self.frame)
        self.asyes1.setGeometry(QtCore.QRect(10, 190, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.asyes1.setFont(font)
        self.asyes1.setObjectName(_fromUtf8("asyes1"))

        self.inputdatalbl = QtGui.QLabel(self.frame) #Do you want to Provide Input data type
        self.inputdatalbl.setGeometry(QtCore.QRect(10, 240, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputdatalbl.setFont(font)
        self.inputdatalbl.setObjectName(_fromUtf8("inputdatalbl"))

        self.inpcmb = QtGui.QComboBox(self.frame)
        self.inpcmb.setToolTip("Select any one of the option")
        self.inpcmb.setGeometry(QtCore.QRect(10, 260, 721, 27))
        self.inpcmb.addItem(_fromUtf8(""))
        self.inpcmb.addItem(_fromUtf8(""))
        self.inpcmb.addItem(_fromUtf8(""))
        self.inpcmb.addItem(_fromUtf8(""))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.inpcmb.setFont(font)
        self.inpcmb.setObjectName(_fromUtf8("inpcmb"))

        self.frame1 = QtGui.QFrame(self.scrollAreaWidgetContents) #frame that containes sam bam cxb option
        self.frame1.setGeometry(QtCore.QRect(50, 10, 741, 3000))
        self.frame1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame1.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
        self.frame1.setObjectName(_fromUtf8("frame1"))

        self.ovrhngtollbl0 = QtGui.QLabel(self.frame1) #Conditions
        self.ovrhngtollbl0.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl0.setFont(font)
        self.ovrhngtollbl0.setObjectName(_fromUtf8("ovrhngtollbl0"))

        self.groupBox = QtGui.QGroupBox(self.frame1)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 711, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))

        self.ovrhngtollbl = QtGui.QLabel(self.groupBox) #Name
        self.ovrhngtollbl.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl.setFont(font)
        self.ovrhngtollbl.setObjectName(_fromUtf8("ovrhngtollbl"))

        self.ovrtoltxt = QtGui.QLineEdit(self.groupBox)
        self.ovrtoltxt.setGeometry(QtCore.QRect(10, 30, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrtoltxt.setFont(font)
        self.ovrtoltxt.setToolTip("Please provide the name for the file")
        self.ovrtoltxt.setObjectName(_fromUtf8("ovrtoltxt"))

        self.subrefanlbl1 = QtGui.QLabel(self.groupBox) # Replicates
        self.subrefanlbl1.setGeometry(QtCore.QRect(10, 80, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanlbl1.setFont(font)
        self.subrefanlbl1.setObjectName(_fromUtf8("subrefanlbl1"))

        self.subrefanpushgrp1 = QtGui.QPushButton(self.groupBox)
        self.subrefanpushgrp1.setGeometry(QtCore.QRect(10, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpushgrp1.setFont(font)
        self.subrefanpushgrp1.setToolTip("Click here to select single file")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subrefanpushgrp1.setIcon(icon)
        self.subrefanpushgrp1.setObjectName(_fromUtf8("subrefanpushgrp1"))

        self.mulfile1 = QtGui.QPushButton(self.groupBox)
        self.mulfile1.setToolTip("Click here to select mutiple file")
        self.mulfile1.setGeometry(QtCore.QRect(50, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile1.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile1.setIcon(icon)
        self.mulfile1.setObjectName(_fromUtf8("mulfile1"))

        self.subrefcombgrp1 = QtGui.QComboBox(self.groupBox)
        self.subrefcombgrp1.setGeometry(QtCore.QRect(90, 100, 601, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.subrefcombgrp1.setFont(font)
        self.subrefcombgrp1.setObjectName(_fromUtf8("subrefcomb"))

        self.groupBox1 = QtGui.QGroupBox(self.frame1) # another groupbox that contain replicates and sam files
        self.groupBox1.setGeometry(QtCore.QRect(10, 170, 711, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox1.setFont(font)
        self.groupBox1.setTitle(_fromUtf8(""))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))

        self.ovrhngtollbl1 = QtGui.QLabel(self.groupBox1) # Name
        self.ovrhngtollbl1.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl1.setFont(font)
        self.ovrhngtollbl1.setObjectName(_fromUtf8("ovrhngtollbl1"))

        self.ovrtoltxt1 = QtGui.QLineEdit(self.groupBox1)
        self.ovrtoltxt1.setToolTip("Please provide the name for the file")
        self.ovrtoltxt1.setGeometry(QtCore.QRect(10, 30, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrtoltxt1.setFont(font)
        self.ovrtoltxt1.setObjectName(_fromUtf8("ovrtoltxt1"))

        self.subrefanlbl = QtGui.QLabel(self.groupBox1)
        self.subrefanlbl.setGeometry(QtCore.QRect(10, 80, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanlbl.setFont(font)
        self.subrefanlbl.setObjectName(_fromUtf8("subrefanlbl"))

        self.subrefanpushgrp2 = QtGui.QPushButton(self.groupBox1)
        self.subrefanpushgrp2.setGeometry(QtCore.QRect(10, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpushgrp2.setFont(font)
        self.subrefanpushgrp2.setToolTip("Click here to select single file")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subrefanpushgrp2.setIcon(icon)
        self.subrefanpushgrp2.setObjectName(_fromUtf8("subrefanpushgrp2"))

        self.mulfile3 = QtGui.QPushButton(self.groupBox1)
        self.mulfile3.setGeometry(QtCore.QRect(50, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile3.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile3.setIcon(icon)
        self.mulfile3.setToolTip("Click here to select multiple file")
        self.mulfile3.setObjectName(_fromUtf8("mulfile3"))

        self.subrefcombgrp2 = QtGui.QComboBox(self.groupBox1)
        self.subrefcombgrp2.setGeometry(QtCore.QRect(90, 100, 601, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.subrefcombgrp2.setFont(font)
        self.subrefcombgrp2.setObjectName(_fromUtf8("subrefcombgrp2"))

        self.subrefanpushp = QtGui.QPushButton(self.frame1)
        self.subrefanpushp.setGeometry(QtCore.QRect(10, 330, 155, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpushp.setFont(font)
        self.subrefanpushp.setText(_fromUtf8(""))
        self.subrefanpushp.setToolTip("Click here to Submite these files and insert some other files")
        self.subrefanpushp.setObjectName(_fromUtf8("subrefanpushp"))

        self.subrefanpushok = QtGui.QPushButton(self.frame1)
        self.subrefanpushok.setGeometry(QtCore.QRect(620, 330, 85, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpushok.setFont(font)
        self.subrefanpushok.setToolTip("Click here to submit these values and go-back to previous menu")
        self.subrefanpushok.setObjectName(_fromUtf8("subrefanpushok"))

        self.sublib = QtGui.QLabel(self.frame) #Select Library normalization method
        self.sublib.setGeometry(QtCore.QRect(10, 310, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sublib.setFont(font)
        self.sublib.setObjectName(_fromUtf8("sublib"))

        self.subrefcomb = QtGui.QComboBox(self.frame)
        self.subrefcomb.setGeometry(QtCore.QRect(10, 330, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.subrefcomb.setFont(font)
        self.subrefcomb.setToolTip("Select any one of the options")
        self.subrefcomb.addItem(_fromUtf8(""))
        self.subrefcomb.addItem(_fromUtf8(""))
        self.subrefcomb.addItem(_fromUtf8(""))
        self.subrefcomb.setObjectName(_fromUtf8("subrefcomb"))

        self.displib = QtGui.QLabel(self.frame) #Select Dispersion estimation method
        self.displib.setGeometry(QtCore.QRect(10, 380, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.displib.setFont(font)
        self.displib.setObjectName(_fromUtf8("displib"))

        self.dispcomb = QtGui.QComboBox(self.frame)
        self.dispcomb.setGeometry(QtCore.QRect(10, 400, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.dispcomb.setFont(font)
        self.dispcomb.setToolTip("Select any one of the options")
        self.dispcomb.addItem(_fromUtf8(""))
        self.dispcomb.addItem(_fromUtf8(""))
        self.dispcomb.addItem(_fromUtf8(""))
        self.dispcomb.addItem(_fromUtf8(""))
        self.dispcomb.setObjectName(_fromUtf8("dispcomb"))

        self.faldlbl = QtGui.QLabel(self.frame) #Set vaue for False Discovery Rate
        self.faldlbl.setGeometry(QtCore.QRect(10, 450, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.faldlbl.setFont(font)
        self.faldlbl.setObjectName(_fromUtf8("faldlbl"))

        self.faldtxt = QtGui.QLineEdit(self.frame)
        self.faldtxt.setGeometry(QtCore.QRect(10, 470, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.faldtxt.setFont(font)
        self.faldtxt.setToolTip("Please Provide integer value")
        self.faldtxt.setObjectName(_fromUtf8("faldtxt"))

        self.faldlbl1 = QtGui.QLabel(self.frame) #Set vaue for Min Alignment Count
        self.faldlbl1.setGeometry(QtCore.QRect(10, 520, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.faldlbl1.setFont(font)
        self.faldlbl1.setObjectName(_fromUtf8("faldlbl1"))

        self.faldtxt1 = QtGui.QLineEdit(self.frame)
        self.faldtxt1.setGeometry(QtCore.QRect(10, 540, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.faldtxt1.setFont(font)
        self.faldtxt1.setToolTip("Please Provide integer value")
        self.faldtxt1.setObjectName(_fromUtf8("faldtxt"))

        self.sqlbl1 = QtGui.QLabel(self.frame) #Do you want to Use multi-read correct
        self.sqlbl1.setGeometry(QtCore.QRect(10, 590, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sqlbl1.setFont(font)
        self.sqlbl1.setObjectName(_fromUtf8("sqlbl1"))

        self.asno11 = QtGui.QPushButton(self.frame)
        self.asno11.setGeometry(QtCore.QRect(60, 610, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.asno11.setFont(font)
        self.asno11.setObjectName(_fromUtf8("asno11"))

        self.asyes11 = QtGui.QPushButton(self.frame)
        self.asyes11.setToolTip(("Click here to Use multi-read correct otherwise click no"))
        self.asyes11.setGeometry(QtCore.QRect(10, 610, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.asyes11.setFont(font)
        self.asyes11.setObjectName(_fromUtf8("asyes11"))

        self.multireadlbl = QtGui.QLabel(self.frame) #Do you want to Include Read Group Datasets
        self.multireadlbl.setGeometry(QtCore.QRect(10, 660, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.multireadlbl.setFont(font)
        self.multireadlbl.setObjectName(_fromUtf8("multireadlbl"))

        self.multireadcmb = QtGui.QComboBox(self.frame)
        self.multireadcmb.setGeometry(QtCore.QRect(10, 680, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.multireadcmb.setFont(font)
        self.multireadcmb.setObjectName(_fromUtf8("multireadcmb"))
        self.multireadcmb.setToolTip("Click yes to include Read Group Datasets otherwise Click No")
        self.multireadcmb.addItem(_fromUtf8(""))
        self.multireadcmb.addItem(_fromUtf8(""))

        self.multireadlbl1 = QtGui.QLabel(self.frame) #Do you want to Include Count Based output files
        self.multireadlbl1.setGeometry(QtCore.QRect(10, 730, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.multireadlbl1.setFont(font)
        self.multireadlbl1.setObjectName(_fromUtf8("multireadlbl1"))

        self.multireadcmb1 = QtGui.QComboBox(self.frame)
        self.multireadcmb1.setGeometry(QtCore.QRect(10, 750, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.multireadcmb1.setFont(font)
        self.multireadcmb1.setObjectName(_fromUtf8("multireadcmb1"))
        self.multireadcmb1.setToolTip("Click yes to include Count Based output files otherwise click No")
        self.multireadcmb1.addItem(_fromUtf8(""))
        self.multireadcmb1.addItem(_fromUtf8(""))

        self.lengthcorlbl = QtGui.QLabel(self.frame) #Do you want to Apply length correction
        self.lengthcorlbl.setGeometry(QtCore.QRect(10, 800, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lengthcorlbl.setFont(font)
        self.lengthcorlbl.setObjectName(_fromUtf8("lengthcorlbl"))

        self.lengthcorcmb = QtGui.QComboBox(self.frame)
        self.lengthcorcmb.setToolTip("Select any one of the following options")
        self.lengthcorcmb.setGeometry(QtCore.QRect(10, 820, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.lengthcorcmb.setFont(font)
        self.lengthcorcmb.setObjectName(_fromUtf8("lengthcorcmb"))
        self.lengthcorcmb.addItem(_fromUtf8(""))
        self.lengthcorcmb.addItem(_fromUtf8(""))
        self.lengthcorcmb.addItem(_fromUtf8(""))

        self.advcufoptlbl = QtGui.QLabel(self.frame) #Do you want to Set Additional Parameters for single end reads
        self.advcufoptlbl.setGeometry(QtCore.QRect(10, 870, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.advcufoptlbl.setFont(font)
        self.advcufoptlbl.setObjectName(_fromUtf8("advcufoptlbl"))

        self.advcufoptcmb = QtGui.QComboBox(self.frame)
        self.advcufoptcmb.setGeometry(QtCore.QRect(10, 890, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.advcufoptcmb.setFont(font)
        self.advcufoptcmb.setObjectName(_fromUtf8("advcufoptcmb"))
        self.advcufoptcmb.setToolTip("Click yes to set additional Cuffdiff option otherwise click No")
        self.advcufoptcmb.addItem(_fromUtf8(""))
        self.advcufoptcmb.addItem(_fromUtf8(""))

        self.groupBox_4 = QtGui.QGroupBox(self.frame) #groupbox that containes additional Cuffdiff option
        self.groupBox_4.setGeometry(QtCore.QRect(10, 910, 741, 1081))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))

        self.avgfraglbl = QtGui.QLabel(self.groupBox_4) #Do you want to set the Average Fragment Length
        self.avgfraglbl.setGeometry(QtCore.QRect(0, 20, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.avgfraglbl.setFont(font)
        self.avgfraglbl.setObjectName(_fromUtf8("avgfraglbl"))

        self.avgtxt = QtGui.QLineEdit(self.groupBox_4)
        self.avgtxt.setGeometry(QtCore.QRect(0, 40, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.avgtxt.setFont(font)
        self.avgtxt.setToolTip("Please provide integer value")
        self.avgtxt.setObjectName(_fromUtf8("avgtxt"))

        self.intdiststddevlbl = QtGui.QLabel(self.groupBox_4) #Do you want to set the Fragment Length Standard Deviation
        self.intdiststddevlbl.setGeometry(QtCore.QRect(0,90, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.intdiststddevlbl.setFont(font)
        self.intdiststddevlbl.setObjectName(_fromUtf8("intdiststddevlbl"))

        self.intdiststddevtxt = QtGui.QLineEdit(self.groupBox_4)
        self.intdiststddevtxt.setToolTip("Please provide integer value")
        self.intdiststddevtxt.setGeometry(QtCore.QRect(0, 110, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.intdiststddevtxt.setFont(font)
        self.intdiststddevtxt.setObjectName(_fromUtf8("intdiststddevtxt"))

        self.advgrp = QtGui.QGroupBox(self.frame)  # groupbox that containes advanced cuffdiff options
        self.advgrp.setGeometry(QtCore.QRect(10, 940, 741, 1081))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.advgrp.setFont(font)
        self.advgrp.setObjectName(_fromUtf8("advgrp"))

        self.advcufoptlbl1 = QtGui.QLabel(self.advgrp) #Do you want to Set Advanced Cuffdiff parameters
        self.advcufoptlbl1.setGeometry(QtCore.QRect(0,0, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.advcufoptlbl1.setFont(font)
        self.advcufoptlbl1.setObjectName(_fromUtf8("advcufoptlbl1"))

        self.advcufoptcmb1 = QtGui.QComboBox(self.advgrp)
        self.advcufoptcmb1.setGeometry(QtCore.QRect(0, 20, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.advcufoptcmb1.setFont(font)
        self.advcufoptcmb1.setObjectName(_fromUtf8("advcufoptcmb"))
        self.advcufoptcmb1.setToolTip("Click yes to set advanced Cuffdiff option otherwise click No")
        self.advcufoptcmb1.addItem(_fromUtf8(""))
        self.advcufoptcmb1.addItem(_fromUtf8(""))

        self.advancegrp = QtGui.QFrame(self.scrollAreaWidgetContents) # frame that containes advanced cuffdiff options
        self.advancegrp.setGeometry(QtCore.QRect(50, 50, 761, 2081))
        self.advancegrp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.advancegrp.setFrameShape(QtGui.QFrame.WinPanel)
        self.advancegrp.setFrameShadow(QtGui.QFrame.Raised)
        self.advancegrp.setLineWidth(10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.advancegrp.setFont(font)
        self.advancegrp.setObjectName(_fromUtf8("advancegrp"))

        self.libinplbl = QtGui.QLabel(self.advancegrp) #Do you want to use Library prep used for input reads
        self.libinplbl.setGeometry(QtCore.QRect(30, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.libinplbl.setFont(font)
        self.libinplbl.setObjectName(_fromUtf8("libinplbl"))

        self.libinpcmb = QtGui.QComboBox(self.advancegrp)
        self.libinpcmb.setGeometry(QtCore.QRect(30, 30, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.libinpcmb.setFont(font)
        self.libinpcmb.setToolTip("Select any one option")
        self.libinpcmb.setObjectName(_fromUtf8("libinpcmb"))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))

        self.masklbl = QtGui.QLabel(self.advancegrp) #Select Mask File
        self.masklbl.setGeometry(QtCore.QRect(30, 80, 711, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.masklbl.setFont(font)
        self.masklbl.setObjectName(_fromUtf8("masklbl"))

        self.maskpush = QtGui.QPushButton(self.advancegrp)
        self.maskpush.setToolTip("Click here to select single mask file")
        self.maskpush.setGeometry(QtCore.QRect(30, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.maskpush.setFont(font)
        self.maskpush.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maskpush.setIcon(icon)
        self.maskpush.setObjectName(_fromUtf8("maskpush"))

        self.mulfile5 = QtGui.QPushButton(self.advancegrp)
        self.mulfile5.setGeometry(QtCore.QRect(70, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile5.setFont(font)
        self.mulfile5.setToolTip("Click here to select mulitiple mask file")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile5.setIcon(icon)
        self.mulfile5.setObjectName(_fromUtf8("mulfile5"))

        self.maskcmb = QtGui.QComboBox(self.advancegrp)
        self.maskcmb.setGeometry(QtCore.QRect(110, 100, 601, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
       # font.setBold(True)
        font.setWeight(50)
        self.maskcmb.setFont(font)
        self.maskcmb.setObjectName(_fromUtf8("maskcmb"))

        self.timlbl = QtGui.QLabel(self.advancegrp) #Do you want to Perform Time Series analysis
        self.timlbl.setGeometry(QtCore.QRect(30, 150, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.timlbl.setFont(font)
        self.timlbl.setObjectName(_fromUtf8("timlbl"))

        self.no1 = QtGui.QPushButton(self.advancegrp)
        self.no1.setGeometry(QtCore.QRect(80, 170, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.no1.setFont(font)
        self.no1.setObjectName(_fromUtf8("no1"))

        self.yes1 = QtGui.QPushButton(self.advancegrp)
        self.yes1.setToolTip("Click here if want to Perform Time Series analysis otherwise Click NO")
        self.yes1.setGeometry(QtCore.QRect(30, 170, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.yes1.setFont(font)
        self.yes1.setObjectName(_fromUtf8("yes1"))

        self.maxmlelbl = QtGui.QLabel(self.advancegrp) #Do you want to set the Max MLE iterations
        self.maxmlelbl.setGeometry(QtCore.QRect(30, 220, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.maxmlelbl.setFont(font)
        self.maxmlelbl.setObjectName(_fromUtf8("maxmlelbl"))

        self.maxmletxt = QtGui.QLineEdit(self.advancegrp)
        self.maxmletxt.setToolTip("Please provide integer value")
        self.maxmletxt.setGeometry(QtCore.QRect(30, 240, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.maxmletxt.setFont(font)
        self.maxmletxt.setObjectName(_fromUtf8("maxmletxt"))

        self.hitslbl1 = QtGui.QLabel(self.advancegrp) #Do you want to Select the Hits included in normalization
        self.hitslbl1.setGeometry(QtCore.QRect(30, 290, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hitslbl1.setFont(font)
        self.hitslbl1.setObjectName(_fromUtf8("hitslbl1"))

        self.hitscmb = QtGui.QComboBox(self.advancegrp)
        self.hitscmb.setToolTip("Select any one option")
        self.hitscmb.setGeometry(QtCore.QRect(30, 310, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.hitscmb.setFont(font)
        self.hitscmb.setObjectName(_fromUtf8("hitscmb"))
        self.hitscmb.addItem(_fromUtf8(""))
        self.hitscmb.addItem(_fromUtf8(""))

        self.maxfraglbl = QtGui.QLabel(self.advancegrp) #Do you want to set Maximum number of fragments per locus
        self.maxfraglbl.setGeometry(QtCore.QRect(30, 360, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.maxfraglbl.setFont(font)
        self.maxfraglbl.setObjectName(_fromUtf8("maxfraglbl"))

        self.maxtxt = QtGui.QLineEdit(self.advancegrp)
        self.maxtxt.setToolTip("Please provide integer values")
        self.maxtxt.setGeometry(QtCore.QRect(30, 380, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.maxtxt.setFont(font)
        self.maxtxt.setObjectName(_fromUtf8("maxtxt"))

        self.numfraglbl = QtGui.QLabel(self.advancegrp) #Do you want to set Number of fragment generation sample
        self.numfraglbl.setGeometry(QtCore.QRect(30, 430, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.numfraglbl.setFont(font)
        self.numfraglbl.setObjectName(_fromUtf8("numfraglbl"))

        self.numtxt = QtGui.QLineEdit(self.advancegrp)
        self.numtxt.setToolTip("Please provide integer values")
        self.numtxt.setGeometry(QtCore.QRect(30, 450, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.numtxt.setFont(font)
        self.numtxt.setObjectName(_fromUtf8("numtxt"))

        self.assamplbl = QtGui.QLabel(self.advancegrp) #Do you want to set Number of fragment assignment samples per generations
        self.assamplbl.setGeometry(QtCore.QRect(30, 500, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.assamplbl.setFont(font)
        self.assamplbl.setObjectName(_fromUtf8("assamplbl"))

        self.asamptxt = QtGui.QLineEdit(self.advancegrp)
        self.asamptxt.setToolTip("Please provide integer values")
        self.asamptxt.setGeometry(QtCore.QRect(30, 520, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.asamptxt.setFont(font)
        self.asamptxt.setObjectName(_fromUtf8("asamptxt"))

        self.minreplbl = QtGui.QLabel(self.advancegrp) #Do you want to set Minimal Replicates for isoform shift testing
        self.minreplbl.setGeometry(QtCore.QRect(30, 570, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.minreplbl.setFont(font)
        self.minreplbl.setObjectName(_fromUtf8("minreplbl"))

        self.minreptxt = QtGui.QLineEdit(self.advancegrp)
        self.minreptxt.setToolTip("Please provide integer values")
        self.minreptxt.setGeometry(QtCore.QRect(30, 590, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.minreptxt.setFont(font)
        self.minreptxt.setObjectName(_fromUtf8("minreptxt"))

        self.otherfrm = QtGui.QFrame(self.advancegrp) #frame that contains other options
        self.otherfrm.setGeometry(QtCore.QRect(20, 640, 791, 1521))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.otherfrm.setFont(font)
        self.otherfrm.setObjectName(_fromUtf8("otherfrm"))

        self.help = QtGui.QLabel(self.otherfrm) #Do you want to Prints the help message
        self.help.setGeometry(QtCore.QRect(10, 20, 511, 17))
        self.help.setObjectName(_fromUtf8("help"))

        self.helpyes = QtGui.QPushButton(self.otherfrm)
        self.helpyes.setToolTip("Click here if you want to Prints the help message otherwise click NO")
        self.helpyes.setGeometry(QtCore.QRect(10, 40, 51, 27))
        self.helpyes.setObjectName(_fromUtf8("helpyes"))

        self.helpno = QtGui.QPushButton(self.otherfrm)
        self.helpno.setGeometry(QtCore.QRect(60, 40, 51, 27))
        self.helpno.setObjectName(_fromUtf8("helpno"))


        self.threadl = QtGui.QLabel(self.otherfrm) #Please enter the  number of alignment threads to launch
        self.threadl.setGeometry(QtCore.QRect(10, 160, 641, 17))
        self.threadl.setObjectName(_fromUtf8("threadl"))

        self.thrdtxt = QtGui.QLineEdit(self.otherfrm)
        self.thrdtxt.setToolTip("Please provide integer values")
        self.thrdtxt.setGeometry(QtCore.QRect(10, 180, 681, 27))
        self.thrdtxt.setObjectName(_fromUtf8("thrdtxt"))

        self.outlb = QtGui.QLabel(self.otherfrm) #Do you want to write all output files to this directory
        self.outlb.setGeometry(QtCore.QRect(10, 90, 541, 17))
        self.outlb.setObjectName(_fromUtf8("outlb"))

        self.outdirtxt = QtGui.QLineEdit(self.otherfrm)
        self.outdirtxt.setToolTip("Please Provide path of the directory")
        self.outdirtxt.setGeometry(QtCore.QRect(10, 110, 681, 27))
        self.outdirtxt.setObjectName(_fromUtf8("outdirtxt"))


        self.idl = QtGui.QLabel(self.otherfrm) #Do you want to assembled transcripts have this ID prefix
        self.idl.setGeometry(QtCore.QRect(10, 230, 711, 17))
        self.idl.setObjectName(_fromUtf8("idl"))

        self.idtxt = QtGui.QLineEdit(self.otherfrm)
        self.idtxt.setToolTip("Please provide ID value")
        self.idtxt.setGeometry(QtCore.QRect(10, 250, 681, 27))
        self.idtxt.setObjectName(_fromUtf8("idtxt"))


        self.biasln = QtGui.QLabel(self.otherfrm) #Do you want to use bias correction
        self.biasln.setGeometry(QtCore.QRect(10, 300, 491, 17))
        self.biasln.setObjectName(_fromUtf8("biasln"))
        self.biastxtcor = QtGui.QComboBox(self.otherfrm)
        self.biastxtcor.setGeometry(QtCore.QRect(90, 320, 601, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.biastxtcor.setFont(font)
        self.biastxtcor.setObjectName(_fromUtf8("biastxtcor"))

        self.biaspus = QtGui.QPushButton(self.otherfrm)
        self.biaspus.setToolTip("Click here to select single file")
        self.biaspus.setGeometry(QtCore.QRect(10, 320, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.biaspus.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.biaspus.setIcon(icon)
        self.biaspus.setObjectName(_fromUtf8("biaspus"))

        self.mulfile4 = QtGui.QPushButton(self.otherfrm)
        self.mulfile4.setGeometry(QtCore.QRect(50, 320, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile4.setFont(font)
        self.mulfile4.setToolTip("Click here to select multiple file for bias correction")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile4.setIcon(icon)
        self.mulfile4.setObjectName(_fromUtf8("mulfile4"))

        self.difanal = QtGui.QLabel(self.otherfrm) #Do you want to generate differential analysis files
        self.difanal.setGeometry(QtCore.QRect(10, 370, 611, 17))
        self.difanal.setObjectName(_fromUtf8("difanal"))

        self.diffno = QtGui.QPushButton(self.otherfrm)
        self.diffno.setGeometry(QtCore.QRect(60, 390, 51, 27))
        self.diffno.setObjectName(_fromUtf8("diffno"))

        self.diffyes = QtGui.QPushButton(self.otherfrm)
        self.diffyes.setToolTip("Click here if you want to generate differential analysis files otherwise click No" )
        self.diffyes.setGeometry(QtCore.QRect(10, 390, 51, 27))
        self.diffyes.setObjectName(_fromUtf8("diffyes"))

        self.iso = QtGui.QLabel(self.otherfrm) #Do you want to perform isoform switching tests
        self.iso.setGeometry(QtCore.QRect(10, 440, 601, 17))
        self.iso.setObjectName(_fromUtf8("iso"))

        self.isono = QtGui.QPushButton(self.otherfrm)
        self.isono.setGeometry(QtCore.QRect(60, 460, 51, 27))
        self.isono.setObjectName(_fromUtf8("isono"))

        self.isoyes = QtGui.QPushButton(self.otherfrm)
        self.isoyes.setToolTip("Click here if you want to perform isoform switching tests otherwise click No")
        self.isoyes.setGeometry(QtCore.QRect(10, 460, 51, 27))
        self.isoyes.setObjectName(_fromUtf8("isoyes"))

        self.dias = QtGui.QLabel(self.otherfrm) #Do you want to Print lots of status updates and other diagnostic information
        self.dias.setGeometry(QtCore.QRect(10, 510, 631, 17))
        self.dias.setObjectName(_fromUtf8("dias"))

        self.printyes = QtGui.QPushButton(self.otherfrm)
        self.printyes.setToolTip("Click here if you want to Print lots of status updates and other diagnostic information otherwise click No")
        self.printyes.setGeometry(QtCore.QRect(10, 530, 51, 27))
        self.printyes.setObjectName(_fromUtf8("printyes"))

        self.prntno = QtGui.QPushButton(self.otherfrm)
        self.prntno.setGeometry(QtCore.QRect(60, 530, 51, 27))
        self.prntno.setObjectName(_fromUtf8("prntno"))

        self.warn = QtGui.QLabel(self.otherfrm) #Do you want to Suppress messages other than serious warnings and errors
        self.warn.setGeometry(QtCore.QRect(10, 580, 611, 17))
        self.warn.setObjectName(_fromUtf8("warn"))

        self.suppno = QtGui.QPushButton(self.otherfrm)
        self.suppno.setGeometry(QtCore.QRect(60, 600, 51, 27))
        self.suppno.setObjectName(_fromUtf8("suppno"))

        self.suppyes = QtGui.QPushButton(self.otherfrm)
        self.suppyes.setToolTip("Click here if you want to Suppress messages other than serious warnings and errors otherwise click No")
        self.suppyes.setGeometry(QtCore.QRect(10, 600, 51, 27))
        self.suppyes.setObjectName(_fromUtf8("suppyes"))

        self.updat = QtGui.QLabel(self.otherfrm) #Do you want to contact server to check for update availability
        self.updat.setGeometry(QtCore.QRect(10, 650, 661, 17))
        self.updat.setObjectName(_fromUtf8("updat"))

        self.servyes = QtGui.QPushButton(self.otherfrm)
        self.servyes.setToolTip("Click here if you want to contact server to check for update availability otherwise click No")
        self.servyes.setGeometry(QtCore.QRect(10, 670, 51, 27))
        self.servyes.setObjectName(_fromUtf8("servyes"))

        self.servno = QtGui.QPushButton(self.otherfrm)
        self.servno.setGeometry(QtCore.QRect(60, 670, 51, 27))
        self.servno.setObjectName(_fromUtf8("servno"))

        self.dispersion = QtGui.QLabel(self.otherfrm) #Want to Use the Poisson fragment dispersion model instead of learning one in each condition
        self.dispersion.setGeometry(QtCore.QRect(10, 720, 771, 17))
        self.dispersion.setObjectName(_fromUtf8("dispersion"))

        self.poisno = QtGui.QPushButton(self.otherfrm)
        self.poisno.setGeometry(QtCore.QRect(60, 740, 51, 27))
        self.poisno.setObjectName(_fromUtf8("poisno"))

        self.Poiyes = QtGui.QPushButton(self.otherfrm)
        self.Poiyes.setToolTip("click here if you Want to Use the Poisson fragment dispersion model instead of learning one in each condition otherwise click No")
        self.Poiyes.setGeometry(QtCore.QRect(10, 740, 51, 27))
        self.Poiyes.setObjectName(_fromUtf8("Poiyes"))

        self.overdisp = QtGui.QLabel(self.otherfrm) #Do you want to print count tables used to fit overdispersion
        self.overdisp.setGeometry(QtCore.QRect(10, 790, 641, 17))
        self.overdisp.setObjectName(_fromUtf8("overdisp"))

        self.tabno = QtGui.QPushButton(self.otherfrm)
        self.tabno.setGeometry(QtCore.QRect(60, 810, 51, 27))
        self.tabno.setObjectName(_fromUtf8("tabno"))

        self.tabyes = QtGui.QPushButton(self.otherfrm)
        self.tabyes.setToolTip("Click here if you want to print count tables used to fit overdispersion otherwise click No")
        self.tabyes.setGeometry(QtCore.QRect(10, 810, 51, 27))
        self.tabyes.setObjectName(_fromUtf8("tabyes"))


        self.skipl = QtGui.QLabel(self.otherfrm) #Set the maximum fragments allowed in a bundle before skipping
        self.skipl.setGeometry(QtCore.QRect(10, 860, 671, 17))
        self.skipl.setObjectName(_fromUtf8("skipl"))

        self.skiptxt = QtGui.QLineEdit(self.otherfrm)
        self.skiptxt.setToolTip("Please provide integer value")
        self.skiptxt.setGeometry(QtCore.QRect(10, 880, 681, 27))
        self.skiptxt.setObjectName(_fromUtf8("skiptxt"))

        self.numsaml = QtGui.QLabel(self.otherfrm) #Set the Number of fragment generation samples
        self.numsaml.setGeometry(QtCore.QRect(10, 930, 641, 17))
        self.numsaml.setObjectName(_fromUtf8("numsaml"))

        self.fragentxsm = QtGui.QLineEdit(self.otherfrm)
        self.fragentxsm.setToolTip("Please provide integer value")
        self.fragentxsm.setGeometry(QtCore.QRect(10, 950, 681, 27))
        self.fragentxsm.setObjectName(_fromUtf8("fragentxsm"))

        self.assgn = QtGui.QLabel(self.otherfrm) #Set the Number of fragment assignment samples per generation
        self.assgn.setGeometry(QtCore.QRect(10, 1000, 731, 17))
        self.assgn.setObjectName(_fromUtf8("assgn"))

        self.pergen = QtGui.QLineEdit(self.otherfrm)
        self.pergen.setToolTip("Please provide integer value")
        self.pergen.setGeometry(QtCore.QRect(10, 1020, 681, 27))
        self.pergen.setObjectName(_fromUtf8("pergen"))

        self.testing = QtGui.QLabel(self.otherfrm) #Set  Replicates needed for relative isoform shift testing
        self.testing.setGeometry(QtCore.QRect(10, 1070, 681, 17))
        self.testing.setObjectName(_fromUtf8("testing"))

        self.pergen_2 = QtGui.QLineEdit(self.otherfrm)
        self.pergen_2.setToolTip("Please provide integer value")
        self.pergen_2.setGeometry(QtCore.QRect(10, 1090, 681, 27))
        self.pergen_2.setObjectName(_fromUtf8("pergen_2"))

        self.ok = QtGui.QPushButton(self.advancegrp)
        self.ok.setGeometry(QtCore.QRect(550, 1800, 98, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.ok.setFont(font)
        self.ok.setToolTip("Click here to goback previous menu")
        self.ok.setObjectName(_fromUtf8("ok"))

        self.execute = QtGui.QPushButton(self.frame)
        self.execute.setToolTip("Click here if you are submit these values")
        self.execute.setGeometry(QtCore.QRect(600, 1030, 98, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.execute.setFont(font)
        self.execute.setObjectName(_fromUtf8("execute"))

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CUFFDIFF", None))
        self.selgtflbl.setText(_translate("MainWindow","Transcripts",None))
        self.omitlbl.setText(_translate("MainWindow", "Do you want to Omit Tabular Datasets.", None))
        self.asno.setText(_translate("MainWindow", "No", None))
        self.asyes.setText(_translate("MainWindow", "Yes", None))
        self.sqlbl.setText(_translate("MainWindow", "Do you want to Generate SQLite.", None))
        self.asno1.setText(_translate("MainWindow", "No", None))
        self.asyes1.setText(_translate("MainWindow", "Yes", None))
        self.inputdatalbl.setText(_translate("MainWindow", "Do you want to Provide Input data type.", None))
        self.inpcmb.setItemText(0, _translate("MainWindow", "SAM/BAM", None))
        self.inpcmb.setItemText(1, _translate("MainWindow", "Cuffquant(CXB)", None))
        self.inpcmb.setItemText(2, _translate("MainWindow", "List of single replicate condition", None))
        self.inpcmb.setItemText(3, _translate("MainWindow", "List of multiple replicate condition", None))
        self.ovrhngtollbl0.setText(_translate("MainWindow", "Conditions.", None))
        self.ovrhngtollbl.setText(_translate("MainWindow", "Name.", None))
        self.ovrhngtollbl1.setText(_translate("MainWindow", "Name.", None))
        self.subrefanlbl1.setText(_translate("MainWindow", "Replicates", None))
        self.subrefanlbl.setText(_translate("MainWindow", "Replicates.", None))
        self.subrefanpushp.setText(_translate("MainWindow", " + Insert condition", None))
        self.sublib.setText(_translate("MainWindow", "Select Library normalization method\n"
        "", None))
        self.subrefcomb.setItemText(0, _translate("MainWindow", "geometric", None))
        self.subrefcomb.setItemText(1, _translate("MainWindow", "classic-fpkm", None))
        self.subrefcomb.setItemText(2, _translate("MainWindow", "quartile", None))
        self.displib.setText(_translate("MainWindow", "Select Dispersion estimation method\n"
        "", None))
        self.dispcomb.setItemText(0, _translate("MainWindow", "pooled", None))
        self.dispcomb.setItemText(1, _translate("MainWindow", "per-condition", None))
        self.dispcomb.setItemText(2, _translate("MainWindow", "blind", None))
        self.dispcomb.setItemText(2, _translate("MainWindow", "poisson", None))
        self.faldlbl.setText(_translate("MainWindow", "Set vaue for False Discovery Rate", None))
        self.faldlbl1.setText(_translate("MainWindow", "Set vaue for Min Alignment Count", None))
        self.sqlbl1.setText(_translate("MainWindow", "Do you want to Use multi-read correct.", None))
        self.asno11.setText(_translate("MainWindow", "No", None))
        self.asyes11.setText(_translate("MainWindow", "Yes", None))
        self.multireadlbl.setText(_translate("MainWindow", "Do you want to Include Read Group Datasets?", None))
        self.multireadcmb.setItemText(0, _translate("MainWindow", "No", None))
        self.multireadcmb.setItemText(1, _translate("MainWindow", "Yes", None))
        self.multireadlbl1.setText(_translate("MainWindow", "Do you want to Include Count Based output files", None))
        self.multireadcmb1.setItemText(0, _translate("MainWindow", "No", None))
        self.multireadcmb1.setItemText(1, _translate("MainWindow", "Yes", None))
        self.lengthcorlbl.setText(_translate("MainWindow", "Do you want to Apply length correction?", None))
        self.lengthcorcmb.setItemText(0, _translate("MainWindow", "Cufflinks Effective Length Correction", None))
        self.lengthcorcmb.setItemText(1, _translate("MainWindow", "Standard alength Correction", None))
        self.lengthcorcmb.setItemText(2, _translate("MainWindow", "No Length Correction at all (use raw counts)", None))
        self.advcufoptlbl.setText(_translate("MainWindow", "Do you want to Set Additional Parameters for single end reads?", None))
        self.advcufoptcmb.setItemText(0, _translate("MainWindow", "Yes", None))
        self.advcufoptcmb.setItemText(1, _translate("MainWindow", "No", None))
        self.avgfraglbl.setText(_translate("MainWindow", "Do you want to set the Average Fragment Length", None))
        self.intdiststddevlbl.setText(_translate("MainWindow", "Do you want to set the Fragment Length Standard Deviation.", None))
        self.advcufoptlbl1.setText(_translate("MainWindow", "Do you want to Set Advanced Cuffdiff parameters? ", None))
        self.advcufoptcmb1.setItemText(0, _translate("MainWindow", "Yes", None))
        self.advcufoptcmb1.setItemText(1, _translate("MainWindow", "No", None))

        self.libinplbl.setText(_translate("MainWindow", "Do you want to use Library prep used for input reads?", None))
        self.libinpcmb.setItemText(0, _translate("MainWindow", "Auto Detect", None))
        self.libinpcmb.setItemText(1, _translate("MainWindow", "ff-firststrand", None))
        self.libinpcmb.setItemText(2, _translate("MainWindow", "ff-secondstrand", None))
        self.libinpcmb.setItemText(3, _translate("MainWindow", "ff-unstranded", None))
        self.libinpcmb.setItemText(4, _translate("MainWindow", "fr-firststrand", None))
        self.libinpcmb.setItemText(5, _translate("MainWindow", "fr-secondstrand", None))
        self.libinpcmb.setItemText(6, _translate("MainWindow", "fr-unstranded", None))
        self.libinpcmb.setItemText(7, _translate("MainWindow", "transfrags", None))
        self.masklbl.setText(_translate("MainWindow", "Select Mask File", None))
        self.timlbl.setText(_translate("MainWindow", "Do you want to Perform Time Series analysis.", None))
        self.no1.setText(_translate("MainWindow", "No", None))
        self.yes1.setText(_translate("MainWindow", "Yes", None))
        self.maxmlelbl.setText(_translate("MainWindow", "Do you want to set the Max MLE iterations.", None))
        self.hitslbl1.setText(_translate("MainWindow", "Do you want to Select the Hits included in normalization?", None))
        self.hitscmb.setItemText(0, _translate("MainWindow", "Compatible Hits", None))
        self.hitscmb.setItemText(1, _translate("MainWindow", "All Hits", None))
        self.maxfraglbl.setText(_translate("MainWindow", "Do you want to set Maximum number of fragments per locus?", None))
        self.numfraglbl.setText(_translate("MainWindow", "Do you want to set Number of fragment generation samples", None))
        self.assamplbl.setText(_translate("MainWindow", "Do you want to set Number of fragment assignment samples per generations", None))
        self.minreplbl.setText(_translate("MainWindow", "Do you want to set Minimal Replicates for isoform shift testing", None))
        self.execute.setText(_translate("MainWindow", "Execute", None))
        self.ok.setText(_translate("MainWindow", "OK", None))
        self.help.setText(_translate("MainWindow", "Do you want to Prints the help message", None))
        self.helpyes.setText(_translate("MainWindow", "Yes", None))
        self.helpno.setText(_translate("MainWindow", "No", None))
        self.threadl.setText(_translate("MainWindow", "Please enter the  number of alignment threads to launch", None))
        self.outlb.setText(_translate("MainWindow", "Do you want to write all output files to this directory  ", None))
        self.idl.setText(_translate("MainWindow", "Do you want to assembled transcripts have this ID prefix", None))

        self.biasln.setText(_translate("MainWindow", "Do you want to use bias correction", None))
        self.biaspus.setToolTip(_translate("MainWindow", "<html><head/><body><p>single</p></body></html>", None))
        self.difanal.setText(_translate("MainWindow", "Do you want to generate differential analysis files", None))
        self.diffno.setText(_translate("MainWindow", "No", None))
        self.diffyes.setText(_translate("MainWindow", "Yes", None))
        self.iso.setText(_translate("MainWindow", "Do you want to perform isoform switching tests", None))
        self.isono.setText(_translate("MainWindow", "No", None))
        self.isoyes.setText(_translate("MainWindow", "Yes", None))
        self.dias.setText(
            _translate("MainWindow", "Do you want to Print lots of status updates and other diagnostic information.",
                       None))
        self.printyes.setText(_translate("MainWindow", "Yes", None))
        self.prntno.setText(_translate("MainWindow", "No", None))
        self.warn.setText(
            _translate("MainWindow", "Do you want to Suppress messages other than serious warnings and errors.", None))
        self.suppno.setText(_translate("MainWindow", "No", None))
        self.suppyes.setText(_translate("MainWindow", "Yes", None))
        self.updat.setText(
            _translate("MainWindow", "Do you want to contact server to check for update availability", None))
        self.servyes.setText(_translate("MainWindow", "Yes", None))
        self.servno.setText(_translate("MainWindow", "No", None))

        self.subrefanpushok.setText(_translate("MainWindow", "OK", None))
        self.dispersion.setText(_translate("MainWindow",
                                           "Want to Use the Poisson fragment dispersion model instead of learning one in each condition.",
                                           None))
        self.poisno.setText(_translate("MainWindow", "No", None))
        self.Poiyes.setText(_translate("MainWindow", "Yes", None))
        self.overdisp.setText(
            _translate("MainWindow", "Do you want to print count tables used to fit overdispersion", None))
        self.tabno.setText(_translate("MainWindow", "No", None))
        self.tabyes.setText(_translate("MainWindow", "Yes", None))
        self.skipl.setText(
            _translate("MainWindow", "Set the maximum fragments allowed in a bundle before skipping", None))
        self.numsaml.setText(_translate("MainWindow", "Set the Number of fragment generation samples", None))
        self.assgn.setText(
            _translate("MainWindow", "Set the Number of fragment assignment samples per generation", None))
        self.testing.setText(
            _translate("MainWindow", "Set  Replicates needed for relative isoform shift testing ", None))

