# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bowtiegui.ui'
#
# Created: Tue Mar  1 14:46:40 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 1500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 1500))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1500))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.centralWidget = QtGui.QWidget(MainWindow)
        layout = QtGui.QVBoxLayout(self.centralWidget)
        layout.addWidget(self.scrollArea)

        #self.scrollArea.setGeometry(QtCore.QRect(0, 0, 41, 111))
        #self.scrollArea.setWidgetResizable(True)
        #self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        #self.scrollAreaWidgetContents = QtGui.QWidget()
       # self.scrollArea.setGeometry(QtCore.QRect(230, 0, 841, 2481))
        self.scrollArea.setFrameShape(QtGui.QFrame.WinPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(7)
        self.scrollArea.setWidgetResizable(False)
       # self.scrollArea.setToolTip("place cursor over the controls for information")

        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 812,1252))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        layout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setGeometry(QtCore.QRect(50, 10, 741, 1200))
        self.frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
        self.frame.setObjectName(_fromUtf8("frame"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)



        self.selgtflbl = QtGui.QLabel(self.frame) # select gtf file output of cufflinks
        self.selgtflbl.setGeometry(QtCore.QRect(10, 30, 291, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.selgtflbl.setFont(font)
        self.selgtflbl.setToolTip("select the GTF file produced by cufflinks")
        self.selgtflbl.setObjectName(_fromUtf8("selgtflbl"))

        self.selfile = QtGui.QPushButton(self.frame)
        self.selfile.setToolTip("Click here to select single GTF files")
        self.selfile.setGeometry(QtCore.QRect(10, 50, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.selfile.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selfile.setIcon(icon)
        self.selfile.setToolTip("click here to select the file")
        self.selfile.setObjectName(_fromUtf8("selfile"))

        self.mulfile = QtGui.QPushButton(self.frame)
        self.mulfile.setToolTip("Click here to select multiple GTF files")
        self.mulfile.setGeometry(QtCore.QRect(40, 50, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile.setIcon(icon)
        self.mulfile.setObjectName(_fromUtf8("mulfile"))

        self.builselcom = QtGui.QComboBox(self.frame)
        self.builselcom.setGeometry(QtCore.QRect(80, 50, 651, 27))
        self.builselcom.setToolTip("Please select the file")
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        #font.setBold(True)
        #font.setPointSize(11)
        #font.setBold(False)
        #font.setItalic(False)
        font.setWeight(50)
        self.builselcom.setFont(font)
        self.builselcom.setObjectName(_fromUtf8("builselcom"))

        self.refanotlbl = QtGui.QLabel(self.frame) #Select Input data type
        self.refanotlbl.setGeometry(QtCore.QRect(10, 100, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.refanotlbl.setFont(font)
        self.refanotlbl.setObjectName(_fromUtf8("refanotlbl"))

        self.refannotcmb = QtGui.QComboBox(self.frame)
        self.refannotcmb.setToolTip("Select any one of the input data type")
        self.refannotcmb.setGeometry(QtCore.QRect(10, 120, 721, 27))
        self.refannotcmb.addItem(_fromUtf8(""))
        self.refannotcmb.addItem(_fromUtf8(""))
        self.refannotcmb.addItem(_fromUtf8(""))
        self.refannotcmb.addItem(_fromUtf8(""))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.refannotcmb.setFont(font)
        self.refannotcmb.setObjectName(_fromUtf8("refannotcmb"))

        self.subrefanlbl1 = QtGui.QLabel(self.frame) #Select Library normalization method
        self.subrefanlbl1.setGeometry(QtCore.QRect(10, 170, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanlbl1.setFont(font)
        self.subrefanlbl1.setObjectName(_fromUtf8("subrefanlbl"))

        self.subrefcomb = QtGui.QComboBox(self.frame)
        self.subrefcomb.setToolTip("Select any one option")
        self.subrefcomb.setGeometry(QtCore.QRect(10, 190, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.subrefcomb.setFont(font)
        self.subrefcomb.addItem(_fromUtf8(""))
        self.subrefcomb.addItem(_fromUtf8(""))
        self.subrefcomb.addItem(_fromUtf8(""))
        self.subrefcomb.setObjectName(_fromUtf8("subrefcomb"))

        self.ovrhngtollbl = QtGui.QLabel(self.frame) #Do you want to Include Read_Group/Attribute Datasets
        self.ovrhngtollbl.setGeometry(QtCore.QRect(10, 240, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl.setFont(font)
        self.ovrhngtollbl.setObjectName(_fromUtf8("ovrhngtollbl"))

        self.spno = QtGui.QComboBox(self.frame)
        self.spno.setGeometry(QtCore.QRect(10, 260, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)

        font.setWeight(50)
        self.spno.setFont(font)
        self.spno.addItem(_fromUtf8(""))
        self.spno.addItem(_fromUtf8(""))
        self.spno.setToolTip("Click Yes to Include Read_Group/Attribute Datasets")
        self.spno.setObjectName(_fromUtf8("spno"))

        self.ovrhngtollbl1 = QtGui.QLabel(self.frame) #Select output_format
        self.ovrhngtollbl1.setGeometry(QtCore.QRect(10, 310, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl1.setFont(font)
        self.ovrhngtollbl1.setObjectName(_fromUtf8("ovrhngtollbl"))


        self.spyes = QtGui.QComboBox(self.frame)
        self.spyes.setGeometry(QtCore.QRect(10, 330, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)

        font.setWeight(50)
        self.spyes.setFont(font)
        self.spyes.setToolTip("Select any one of the outputformat")
        self.spyes.addItem(_fromUtf8(""))
        self.spyes.addItem(_fromUtf8(""))
        self.spyes.setObjectName(_fromUtf8("spyes"))


        self.biaslbl = QtGui.QLabel(self.frame) #Do you want to Set Advanced Cuffnorm parameters
        self.biaslbl.setGeometry(QtCore.QRect(10, 380, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.biaslbl.setFont(font)
        self.biaslbl.setObjectName(_fromUtf8("biaslbl"))

        self.biascmb = QtGui.QComboBox(self.frame)
        self.biascmb.setToolTip("Click yes to Set Advanced Cuffnorm parameters")
        self.biascmb.setGeometry(QtCore.QRect(10, 400, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.biascmb.setFont(font)
        self.biascmb.setObjectName(_fromUtf8("biascmb"))
        self.biascmb.addItem(_fromUtf8(""))
        self.biascmb.addItem(_fromUtf8(""))

        self.groupBox_4 = QtGui.QFrame(self.frame) # frame that contain advance cuffnorm option
        self.groupBox_4.setGeometry(QtCore.QRect(10, 440, 741, 500))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))

        self.libinplbl = QtGui.QLabel(self.groupBox_4) #Do you want to use Library prep used for input reads
        self.libinplbl.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.libinplbl.setFont(font)
        self.libinplbl.setObjectName(_fromUtf8("libinplbl"))

        self.libinpcmb = QtGui.QComboBox(self.groupBox_4)
        self.libinpcmb.setToolTip("Select any one of the options")
        self.libinpcmb.setGeometry(QtCore.QRect(10, 30, 711, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.libinpcmb.setFont(font)
        self.libinpcmb.setObjectName(_fromUtf8("libinpcmb"))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))
        self.libinpcmb.addItem(_fromUtf8(""))

        self.biaslbl1 = QtGui.QLabel(self.groupBox_4) #Do you want to Select the Hits included in normalization
        self.biaslbl1.setGeometry(QtCore.QRect(10, 80, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.biaslbl1.setFont(font)
        self.biaslbl1.setObjectName(_fromUtf8("biaslbl"))

        self.biascmb1 = QtGui.QComboBox(self.groupBox_4)
        self.biascmb1.setToolTip("Select any one of hits")
        self.biascmb1.setGeometry(QtCore.QRect(10, 100, 711, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.biascmb1.setFont(font)
        self.biascmb1.setObjectName(_fromUtf8("biascmb"))
        self.biascmb1.addItem(_fromUtf8(""))
        self.biascmb1.addItem(_fromUtf8(""))

        self.addtnfrm = QtGui.QFrame(self.groupBox_4) #frame that containe additional information
        self.addtnfrm.setGeometry(QtCore.QRect(0, 150, 721, 801))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addtnfrm.setFont(font)
        self.addtnfrm.setObjectName(_fromUtf8("addtnfrm"))

        self.help = QtGui.QLabel(self.addtnfrm) #Do you want to Prints the help message
        self.help.setGeometry(QtCore.QRect(10, 10, 511, 17))
        self.help.setObjectName(_fromUtf8("help"))

        self.helpyes = QtGui.QPushButton(self.addtnfrm)
        self.helpyes.setGeometry(QtCore.QRect(10, 30, 51, 27))
        self.helpyes.setToolTip("Click here if you want to Prints the help message otherwise click NO")
        self.helpyes.setObjectName(_fromUtf8("helpyes"))
        self.helpno = QtGui.QPushButton(self.addtnfrm)
        self.helpno.setGeometry(QtCore.QRect(60, 30, 51, 27))
        self.helpno.setObjectName(_fromUtf8("helpno"))

       #Do you want to Suppress messages other than serious warnings and errors
        self.warn = QtGui.QLabel(self.addtnfrm)
        self.warn.setGeometry(QtCore.QRect(10, 290, 611, 17))
        self.warn.setObjectName(_fromUtf8("warn"))
        self.suppyes = QtGui.QPushButton(self.addtnfrm)
        self.suppyes.setGeometry(QtCore.QRect(10, 310, 51, 27))
        self.suppyes.setObjectName(_fromUtf8("suppyes"))
        self.suppyes.setToolTip("Click here if you want to Suppress messages other than serious warnings and errors otherwise click No")
        self.suppno = QtGui.QPushButton(self.addtnfrm)
        self.suppno.setGeometry(QtCore.QRect(60, 310, 51, 27))
        self.suppno.setObjectName(_fromUtf8("suppno"))




        self.updat = QtGui.QLabel(self.addtnfrm) #Do you want to contact server to check for update availability
        self.updat.setGeometry(QtCore.QRect(10, 360, 661, 17))
        self.updat.setObjectName(_fromUtf8("updat"))
        self.servyes = QtGui.QPushButton(self.addtnfrm)
        self.servyes.setGeometry(QtCore.QRect(10, 380, 51, 27))
        self.servyes.setToolTip("Click here if you want to contact server to check for update availability otherwise click No")
        self.servyes.setObjectName(_fromUtf8("servyes"))
        self.servno = QtGui.QPushButton(self.addtnfrm)
        self.servno.setGeometry(QtCore.QRect(60, 380, 51, 27))
        self.servno.setObjectName(_fromUtf8("servno"))

        self.diag = QtGui.QLabel(self.addtnfrm) #Do you want to contact server to check for update availability
        self.diag.setGeometry(QtCore.QRect(10, 220, 631, 17))
        self.diag.setObjectName(_fromUtf8("diag"))
        self.printyes = QtGui.QPushButton(self.addtnfrm)
        self.printyes.setToolTip("Click here if you want to Print lots of status updates and other diagnostic information otherwise click No")
        self.printyes.setGeometry(QtCore.QRect(10, 240, 51, 27))
        self.printyes.setObjectName(_fromUtf8("printyes"))
        self.prntno = QtGui.QPushButton(self.addtnfrm)
        self.prntno.setGeometry(QtCore.QRect(60, 240, 51, 27))
        self.prntno.setObjectName(_fromUtf8("prntno"))


        self.outlb = QtGui.QLabel(self.addtnfrm) #Do you want to write all output files to this directory
        self.outlb.setGeometry(QtCore.QRect(10, 80, 541, 17))
        self.outlb.setObjectName(_fromUtf8("outlb"))
        self.outdirtxt = QtGui.QLineEdit(self.addtnfrm)
        self.outdirtxt.setGeometry(QtCore.QRect(10, 100, 711, 27))
        self.outdirtxt.setToolTip("Please provide path of the directory")
        self.outdirtxt.setObjectName(_fromUtf8("outdirtxt"))

        self.threadl = QtGui.QLabel(self.addtnfrm) #Please enter the  number of alignment threads to launch
        self.threadl.setGeometry(QtCore.QRect(10, 150, 641, 17))
        self.threadl.setObjectName(_fromUtf8("threadl"))

        self.thrdtxt = QtGui.QLineEdit(self.addtnfrm)
        self.thrdtxt.setToolTip("Please provide integer value")
        self.thrdtxt.setGeometry(QtCore.QRect(10, 170, 711, 27))
        self.thrdtxt.setText(_fromUtf8(""))
        self.thrdtxt.setObjectName(_fromUtf8("thrdtxt"))

        self.frame1 = QtGui.QFrame(self.scrollAreaWidgetContents_2) #frame optionthat containes sam bam cxb
        self.frame1.setGeometry(QtCore.QRect(50, 10, 741, 3000))
        self.frame1.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame1.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
        self.frame1.setObjectName(_fromUtf8("frame1"))

        self.ovrhngtollbl10 = QtGui.QLabel(self.frame1)# conditions
        self.ovrhngtollbl10.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl10.setFont(font)
        self.ovrhngtollbl10.setObjectName(_fromUtf8("ovrhngtollbl10"))

        self.groupBox = QtGui.QGroupBox(self.frame1)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 711, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))

        self.ovrhngtollbll = QtGui.QLabel(self.groupBox) #Name
        self.ovrhngtollbll.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbll.setFont(font)
        self.ovrhngtollbll.setObjectName(_fromUtf8("ovrhngtollbll"))

        self.ovrtoltxt11 = QtGui.QLineEdit(self.groupBox)
        self.ovrtoltxt11.setToolTip("Please provide Name for the file")
        self.ovrtoltxt11.setGeometry(QtCore.QRect(10, 30, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrtoltxt11.setFont(font)
        self.ovrtoltxt11.setObjectName(_fromUtf8("ovrtoltxt1"))

        self.subrefanlbl11 = QtGui.QLabel(self.groupBox) #Replicates
        self.subrefanlbl11.setGeometry(QtCore.QRect(10, 80, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanlbl11.setFont(font)
        self.subrefanlbl11.setObjectName(_fromUtf8("subrefanlbl11"))

        self.subrefanpush11 = QtGui.QPushButton(self.groupBox)
        self.subrefanpush11.setToolTip("Click here to select single file")
        self.subrefanpush11.setGeometry(QtCore.QRect(10, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpush11.setFont(font)
        self.subrefanpush11.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subrefanpush11.setIcon(icon)
        self.subrefanpush11.setObjectName(_fromUtf8("subrefanpush11"))

        self.mulfile51 = QtGui.QPushButton(self.groupBox)
        self.mulfile51.setToolTip("Click here to select multiple file")
        self.mulfile51.setGeometry(QtCore.QRect(40, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile51.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile51.setIcon(icon)
        self.mulfile51.setObjectName(_fromUtf8("mulfile51"))

        self.subrefcomb11 = QtGui.QComboBox(self.groupBox)
        self.subrefcomb11.setGeometry(QtCore.QRect(80, 100, 611, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.subrefcomb11.setFont(font)
        self.subrefcomb11.setObjectName(_fromUtf8("subrefcomb1"))

        self.groupBox1 = QtGui.QGroupBox(self.frame1)# groupbox that contains sam bam cxb file
        self.groupBox1.setGeometry(QtCore.QRect(10, 170, 711, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox1.setFont(font)
        self.groupBox1.setTitle(_fromUtf8(""))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))

        self.ovrhngtollbl11 = QtGui.QLabel(self.groupBox1) # Name
        self.ovrhngtollbl11.setGeometry(QtCore.QRect(10, 10, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrhngtollbl11.setFont(font)
        self.ovrhngtollbl11.setObjectName(_fromUtf8("ovrhngtollbl11"))

        self.ovrtoltxt111 = QtGui.QLineEdit(self.groupBox1)
        self.ovrtoltxt111.setToolTip("Please provide name for that file")
        self.ovrtoltxt111.setGeometry(QtCore.QRect(10, 30, 681, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ovrtoltxt111.setFont(font)
        self.ovrtoltxt111.setObjectName(_fromUtf8("ovrtoltxt11"))

        self.subrefanlbll = QtGui.QLabel(self.groupBox1)# replicates
        self.subrefanlbll.setGeometry(QtCore.QRect(10, 80, 711, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanlbll.setFont(font)
        self.subrefanlbll.setObjectName(_fromUtf8("subrefanlbll"))

        self.subrefanpush111 = QtGui.QPushButton(self.groupBox1)
        self.subrefanpush111.setToolTip("Click here to select single file")
        self.subrefanpush111.setGeometry(QtCore.QRect(10, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpush111.setFont(font)
        self.subrefanpush111.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subrefanpush111.setIcon(icon)
        self.subrefanpush111.setObjectName(_fromUtf8("subrefanpush111"))

        self.mulfile5 = QtGui.QPushButton(self.groupBox1)
        self.mulfile5.setToolTip("Click here to select single file")
        self.mulfile5.setGeometry(QtCore.QRect(40, 100, 31, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.mulfile5.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index1.png")),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mulfile5.setIcon(icon)
        self.mulfile5.setObjectName(_fromUtf8("mulfile5"))

        self.subrefcomb111 = QtGui.QComboBox(self.groupBox1)
        self.subrefcomb111.setGeometry(QtCore.QRect(70, 100, 621, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        #font.setBold(True)
        font.setWeight(50)
        self.subrefcomb111.setFont(font)
        self.subrefcomb111.setObjectName(_fromUtf8("subrefcomb11"))

        self.subrefanpushp = QtGui.QPushButton(self.frame1)
        self.subrefanpushp.setGeometry(QtCore.QRect(10, 330, 155, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpushp.setFont(font)
        self.subrefanpushp.setText(_fromUtf8(""))
        self.subrefanpushp.setToolTip("Click here to submit these files and insert some other files")
        self.subrefanpushp.setObjectName(_fromUtf8("subrefanpushp"))

        self.subrefanpushok = QtGui.QPushButton(self.frame1)
        self.subrefanpushok.setToolTip("Click here to go-back")
        self.subrefanpushok.setGeometry(QtCore.QRect(620, 330, 85, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.subrefanpushok.setFont(font)
        self.subrefanpushok.setText(_fromUtf8(""))
        self.subrefanpushok.setObjectName(_fromUtf8("subrefanpushok"))


        self.Execute = QtGui.QPushButton(self.frame)
        self.Execute.setGeometry(QtCore.QRect(560, 500, 98, 27))
        self.Execute.setToolTip("Click here if you are submit these values")
        self.Execute.setObjectName(_fromUtf8("Execute"))

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CUFFNORM", None))

        self.selgtflbl.setText(_translate("MainWindow", "Select the transcripts?\n"
"", None))
        self.refanotlbl.setText(_translate("MainWindow", "Select Input data type?\n""",None))
        self.refannotcmb.setItemText(0, _translate("MainWindow", "SAM/BAM", None))
        self.refannotcmb.setItemText(1, _translate("MainWindow", "Cuffquant(CXB)", None))
        self.refannotcmb.setItemText(2, _translate("MainWindow", "List of single replicate condition", None))
        self.refannotcmb.setItemText(3, _translate("MainWindow", "List of multiple replicate condition", None))
        self.subrefanlbl1.setText(_translate("MainWindow", "Select Library normalization method\n"
"", None))
        self.subrefcomb.setItemText(0, _translate("MainWindow", "geometric", None))
        self.subrefcomb.setItemText(1, _translate("MainWindow", "classic-fpkm", None))
        self.subrefcomb.setItemText(2, _translate("MainWindow", "quartile", None))


        self.ovrhngtollbl.setText(_translate("MainWindow", "Do you want to Include Read_Group/Attribute Datasets", None))
        self.spno.setItemText(0, _translate("MainWindow", "Yes", None))
        self.spno.setItemText(1, _translate("MainWindow", "No", None))

        self.ovrhngtollbl1.setText(_translate("MainWindow", "Select output_format", None))
        self.spyes.setItemText(0, _translate("MainWindow", "Simple Table", None))
        self.spyes.setItemText(1, _translate("MainWindow", "Cuffdiff Format", None))


        self.biaslbl.setText(_translate("MainWindow", "Do you want to Set Advanced Cuffnorm parameters?", None))
        self.biascmb.setItemText(0, _translate("MainWindow", "No", None))
        self.biascmb.setItemText(1, _translate("MainWindow", "Yes", None))
        self.libinplbl.setText(_translate("MainWindow", "Do you want to use Library prep used for input reads?", None))
        self.libinpcmb.setItemText(0, _translate("MainWindow", "Auto Detect", None))
        self.libinpcmb.setItemText(1, _translate("MainWindow", "ff-firststrand", None))
        self.libinpcmb.setItemText(2, _translate("MainWindow", "ff-secondstrand", None))
        self.libinpcmb.setItemText(3, _translate("MainWindow", "ff-unstranded", None))
        self.libinpcmb.setItemText(4, _translate("MainWindow", "fr-firststrand", None))
        self.libinpcmb.setItemText(5, _translate("MainWindow", "fr-secondstrand", None))
        self.libinpcmb.setItemText(6, _translate("MainWindow", "fr-unstranded", None))
        self.libinpcmb.setItemText(7, _translate("MainWindow", "transfrags", None))
        self.biaslbl1.setText(_translate("MainWindow", "Do you want to Select the Hits included in normalization?", None))
        self.biascmb1.setItemText(0, _translate("MainWindow", "Compatible Hits", None))
        self.biascmb1.setItemText(1, _translate("MainWindow", "All Hits", None))
        self.Execute.setText(_translate("MainWindow", "Execute", None))
        self.ovrhngtollbl10.setText(_translate("MainWindow", "Conditions.", None))
        self.ovrhngtollbll.setText(_translate("MainWindow", "Name.", None))
        self.ovrhngtollbl11.setText(_translate("MainWindow", "Name.", None))
        self.subrefanlbl11.setText(_translate("MainWindow", "Replicates", None))
        self.subrefanlbll.setText(_translate("MainWindow", "Replicates.", None))
        self.subrefanpushp.setText(_translate("MainWindow", " + Insert condition", None))
        self.suppyes.setText(_translate("MainWindow", "Yes", None))
        self.helpno.setText(_translate("MainWindow", "No", None))
        self.prntno.setText(_translate("MainWindow", "No", None))
        self.servno.setText(_translate("MainWindow", "No", None))
        self.warn.setText(
            _translate("MainWindow", "Do you want to Suppress messages other than serious warnings and errors.", None))
        self.servyes.setText(_translate("MainWindow", "Yes", None))
        self.printyes.setText(_translate("MainWindow", "Yes", None))
        self.helpyes.setText(_translate("MainWindow", "Yes", None))
        self.updat.setText(
            _translate("MainWindow", "Do you want to contact server to check for update availability", None))
        self.diag.setText(
            _translate("MainWindow", "Do you want to Print lots of status updates and other diagnostic information.",
                       None))
        self.help.setText(_translate("MainWindow", "Do you want to Prints the help message", None))
        self.outlb.setText(_translate("MainWindow", "Do you want to write all output files to this directory  ", None))
        self.suppno.setText(_translate("MainWindow", "No", None))
        self.threadl.setText(_translate("MainWindow", "Please enter the  number of alignment threads to launch", None))
        self.subrefanpushok.setText(_translate("MainWindow", "OK", None))

