# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bowtiegui.ui'
#
# Created: Tue Mar  1 14:46:40 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 1500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 1500))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1500))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.centralWidget = QtGui.QWidget(MainWindow)
        layout = QtGui.QVBoxLayout(self.centralWidget)
        layout.addWidget(self.scrollArea)

        #self.scrollArea.setGeometry(QtCore.QRect(0, 0, 41, 111))
        #self.scrollArea.setWidgetResizable(True)
        #self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        #self.scrollAreaWidgetContents = QtGui.QWidget()
       # self.scrollArea.setGeometry(QtCore.QRect(230, 0, 841, 2481))
        self.scrollArea.setFrameShape(QtGui.QFrame.WinPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(7)
        self.scrollArea.setWidgetResizable(False)

        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 812,900))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        layout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setGeometry(QtCore.QRect(30, 10, 760, 850))
        self.frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
        self.frame.setObjectName(_fromUtf8("frame"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        #self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        #MainWindow.setCentralWidget(self.centralWidget)

        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 391, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.sing = QtGui.QPushButton(self.frame)
        self.sing.setGeometry(QtCore.QRect(10, 30, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sing.setIcon(icon)
        font.setWeight(50)
        self.sing.setFont(font)
        self.sing.setObjectName(_fromUtf8("sing"))
        self.sing.setToolTip("Pick a GTF file produced by cufflinks")
        self.cmbgtf = QtGui.QComboBox(self.frame)
        self.cmbgtf.setGeometry(QtCore.QRect(80, 30, 650, 27))
        self.cmbgtf.setObjectName(_fromUtf8("cmbgtf"))

        self.cmbgtf.setFont(font)
        self.cmbgtf.setToolTip("GTF file produced by cufflinks")
        ##self.rep.setGeometry(QtCore.QRect(10, 80, 150, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #font.setWeight(50)
        #self.rep.setFont(font)
        #self.rep.setObjectName(_fromUtf8("rep"))
        ##self.grprep.setTitle(_fromUtf8(""))
        ##self.frame_1 = QtGui.QFrame(self.grprep)
        #self.frame_1.setGeometry(QtCore.QRect(10, 10, 760, 600))
       ## self.frame_1.setFrameShape(QtGui.QFrame.WinPanel)
       # self.frame_1.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
       # self.frame_1.setObjectName(_fromUtf8("frame_1"))
        self.label_36 = QtGui.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(10, 80, 391, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.fileu = QtGui.QPushButton(self.frame)
        self.fileu.setGeometry(QtCore.QRect(10, 100, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileu.setIcon(icon)
        font.setWeight(50)
        self.fileu.setFont(font)
        self.fileu.setObjectName(_fromUtf8("fileu"))
        self.fileu.setToolTip("Pick a .sam or .bam file")
        self.cmbfile = QtGui.QComboBox(self.frame)
        self.cmbfile.setGeometry(QtCore.QRect(80, 100, 650, 27))
        self.cmbfile.setObjectName(_fromUtf8("cmbref"))

        self.cmbfile.setFont(font)
        self.cmbfile.setToolTip("It displays the path of .sam or .bam file")
        #self.addre = QtGui.QPushButton(self.grprep)
        #self.addre.setGeometry(QtCore.QRect(20, 90, 150, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #font.setWeight(50)
        #self.addre.setFont(font)
        #self.addre.setObjectName(_fromUtf8("addre"))
        ##self.clo.setGeometry(QtCore.QRect(500, 90, 51, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #font.setWeight(50)
        #3self.clo.setFont(font)
        #self.clo.setObjectName(_fromUtf8("clo"))
        self.grprepli= QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grprepli.setGeometry(QtCore.QRect(10, 80, 801, 800))
        self.grprepli.setTitle(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.grprepli)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 391, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.filep = QtGui.QPushButton(self.grprepli)
        self.filep.setGeometry(QtCore.QRect(20, 40, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filep.setIcon(icon)
        font.setWeight(50)
        self.filep.setFont(font)
        self.filep.setObjectName(_fromUtf8("filep"))
        self.cmbfilep = QtGui.QComboBox(self.grprepli)
        self.cmbfilep.setGeometry(QtCore.QRect(80, 40, 650, 27))
        self.cmbfilep.setObjectName(_fromUtf8("cmbfilep"))
        #self.cmbfilep.addItem(_fromUtf8(""))
        self.cmbfilep.setFont(font)


        self.label_37 = QtGui.QLabel(self.frame)
        self.label_37.setGeometry(QtCore.QRect(10, 150, 391, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(True)
        font.setPointSize(12)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.mulyes = QtGui.QPushButton(self.frame)
        self.mulyes.setGeometry(QtCore.QRect(10, 170, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.mulyes.setFont(font)
        self.mulyes.setObjectName(_fromUtf8("mulyes"))
        self.mulyes.setToolTip("Click Yes to use multi read correct")
        self.mulno = QtGui.QPushButton(self.frame)
        self.mulno.setGeometry(QtCore.QRect(60, 170, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.mulno.setFont(font)
        self.mulno.setObjectName(_fromUtf8("mulno"))
        self.mulno.setToolTip("Click No to provide default value")
        ##self.label_3 = QtGui.QLabel(self.frame)
        #self.label_3.setGeometry(QtCore.QRect(10, 200, 391, 17))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setBold(True)
        #font.setPointSize(12)
        #font.setWeight(75)
        ##self.label_3.setFont(font)
        #self.label_3.setObjectName(_fromUtf8("label_3"))
        #self.cmbper = QtGui.QComboBox(self.frame)
        #self.cmbper.setGeometry(QtCore.QRect(10, 220, 721, 27))
        #self.cmbper.setObjectName(_fromUtf8("cmbper"))
        #self.cmbper.addItem(_fromUtf8(""))
        #self.cmbper.addItem(_fromUtf8(""))
        #self.cmbper.setFont(font)
        self.grpper = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grpper.setGeometry(QtCore.QRect(10, 10, 841, 300))
        self.grpper.setTitle(_fromUtf8(""))
        self.grpper.setObjectName(_fromUtf8("grpper"))
        self.frame_2 = QtGui.QFrame(self.grpper)
        self.frame_2.setGeometry(QtCore.QRect(00, 10, 750, 200))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(14)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_16 = QtGui.QLabel(self.grpper)
        self.label_16.setGeometry(QtCore.QRect(0, 20, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cmbseq = QtGui.QComboBox(self.grpper)
        self.cmbseq.setGeometry(QtCore.QRect(0, 40, 721, 27))
        self.cmbseq.setObjectName(_fromUtf8("cmbseq"))
        self.cmbseq.addItem(_fromUtf8(""))
        self.cmbseq.addItem(_fromUtf8(""))
        self.cmbseq.setFont(font)
        self.grplocal = QtGui.QGroupBox(self.grpper)
        self.grplocal.setGeometry(QtCore.QRect(10, 60, 841, 150))
        self.grplocal.setTitle(_fromUtf8(""))
        self.grplocal.setObjectName(_fromUtf8("grplocal"))
        self.label_17 = QtGui.QLabel(self.grplocal)
        self.label_17.setGeometry(QtCore.QRect(10, 30, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.cmbgen= QtGui.QComboBox(self.grplocal)
        self.cmbgen.setGeometry(QtCore.QRect(0, 50, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cmbgen.setFont(font)
        self.cmbgen.setObjectName(_fromUtf8("cmbgen"))
        self.cmbgen.addItem(_fromUtf8(""))
        self.grphis = QtGui.QGroupBox(self.grpper)
        self.grphis.setGeometry(QtCore.QRect(10, 60, 841, 131))
        self.grphis.setTitle(_fromUtf8(""))
        self.grphis.setObjectName(_fromUtf8("grphis"))
        self.label_18 = QtGui.QLabel(self.grphis)
        self.label_18.setGeometry(QtCore.QRect(0, 30, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.fil = QtGui.QPushButton(self.grphis)
        self.fil.setGeometry(QtCore.QRect(0, 50, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fil.setIcon(icon)
        font.setWeight(50)
        self.fil.setFont(font)
        self.fil.setObjectName(_fromUtf8("fil"))
        self.cmbfil = QtGui.QComboBox(self.grphis)
        self.cmbfil.setGeometry(QtCore.QRect(70, 50, 650, 27))
        self.cmbfil.setObjectName(_fromUtf8("cmbfil"))
        self.cmbfil.addItem(_fromUtf8(""))
        self.cmbfil.setFont(font)
        self.ok = QtGui.QPushButton(self.grpper)
        self.ok.setGeometry(QtCore.QRect(100, 160, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.ok.setFont(font)
        self.ok.setObjectName(_fromUtf8("ok"))
        self.label_19 = QtGui.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(10, 220, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.cmbapp = QtGui.QComboBox(self.frame)
        self.cmbapp.setGeometry(QtCore.QRect(10, 240, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cmbapp.setFont(font)
        self.cmbapp.setObjectName(_fromUtf8("cmbapp"))
        self.cmbapp.addItem(_fromUtf8(""))
        self.cmbapp.addItem(_fromUtf8(""))
        self.cmbapp.setToolTip("Select to apply length correction")
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(10, 290, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cmbset= QtGui.QComboBox(self.frame)
        self.cmbset.setGeometry(QtCore.QRect(10, 310, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cmbset.setFont(font)
        self.cmbset.setObjectName(_fromUtf8("cmbset"))
        self.cmbset.addItem(_fromUtf8(""))
        self.cmbset.addItem(_fromUtf8(""))
        self.cmbset.setToolTip("Click Yes to set additional paramter and No to provide default value")
        self.grpset = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grpset.setGeometry(QtCore.QRect(10, 10, 841, 300))
        self.grpset.setTitle(_fromUtf8(""))
        self.grpset.setObjectName(_fromUtf8("grpset"))
        self.frame_2 = QtGui.QFrame(self.grpset)
        self.frame_2.setGeometry(QtCore.QRect(00, 10, 800, 200))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(14)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_21 = QtGui.QLabel(self.grpset)
        self.label_21.setGeometry(QtCore.QRect(10,20 , 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.avg = QtGui.QLineEdit(self.grpset)
        self.avg.setGeometry(QtCore.QRect(10,40, 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.avg.setFont(font)
        self.avg.setObjectName(_fromUtf8("avg"))
        self.avg.setToolTip("It takes integer value")
        self.label_22 = QtGui.QLabel(self.grpset)
        self.label_22.setGeometry(QtCore.QRect(10, 90, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.frag = QtGui.QLineEdit(self.grpset)
        self.frag.setGeometry(QtCore.QRect(10,110, 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frag.setFont(font)
        self.frag.setObjectName(_fromUtf8("frag"))
        self.frag.setToolTip("It takes integer value")
        self.bck = QtGui.QPushButton(self.grpset)
        self.bck.setGeometry(QtCore.QRect(100, 170, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.bck.setFont(font)
        self.bck.setObjectName(_fromUtf8("bck"))
        self.bck.setToolTip("Goes back to main page")
        self.label_27 = QtGui.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(10, 360, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.cmbpar = QtGui.QComboBox(self.frame)
        self.cmbpar.setGeometry(QtCore.QRect(10, 380, 721, 27))
        self.cmbpar.setObjectName(_fromUtf8("cmbpar"))
        self.cmbpar.addItem(_fromUtf8(""))
        self.cmbpar.addItem(_fromUtf8(""))
        self.cmbpar.setFont(font)
        self.cmbpar.setToolTip("Click Yes to set Advanced Cuffquqnt parameter and No to provide default value")
        self.grpcuff = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grpcuff.setGeometry(QtCore.QRect(10, 10, 841, 500))
        self.grpcuff.setTitle(_fromUtf8(""))
        self.grpcuff.setObjectName(_fromUtf8("grpcuff"))
        self.frame_3 = QtGui.QFrame(self.grpcuff)
        self.frame_3.setGeometry(QtCore.QRect(00, 10, 800, 400))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_3.setLineWidth(14)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_23 = QtGui.QLabel(self.grpcuff)
        self.label_23.setGeometry(QtCore.QRect(10, 30, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.cmblib = QtGui.QComboBox(self.grpcuff)
        self.cmblib.setGeometry(QtCore.QRect(10, 50, 721, 27))
        self.cmblib.setObjectName(_fromUtf8("cmblib"))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.addItem(_fromUtf8(""))
        self.cmblib.setFont(font)
        self.cmblib.setToolTip("Select Library Type")
        self.label_24 = QtGui.QLabel(self.grpcuff)
        self.label_24.setGeometry(QtCore.QRect(10, 100, 771, 17))

        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.mask = QtGui.QPushButton(self.grpcuff)
        self.mask.setGeometry(QtCore.QRect(10, 120, 60, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mask.setIcon(icon)
        font.setWeight(50)
        self.mask.setFont(font)
        self.mask.setObjectName(_fromUtf8("mask"))
        self.mask.setToolTip("Pick a mask file")
        self.cmbmask = QtGui.QComboBox(self.grpcuff)
        self.cmbmask.setGeometry(QtCore.QRect(70, 120, 655, 27))
        self.cmbmask.setObjectName(_fromUtf8("cmbfile"))
        self.cmbmask.addItem(_fromUtf8(""))
        self.cmbmask.setFont(font)
        self.cmbmask.setToolTip("Displays the path of mask file")
        self.label_25 = QtGui.QLabel(self.grpcuff)
        self.label_25.setGeometry(QtCore.QRect(10, 170, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.max = QtGui.QLineEdit(self.grpcuff)
        self.max.setGeometry(QtCore.QRect(10,190 , 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.max.setFont(font)
        self.max.setObjectName(_fromUtf8("max"))
        self.max.setToolTip("It takes integer value")
        self.label_26 = QtGui.QLabel(self.grpcuff)
        self.label_26.setGeometry(QtCore.QRect(10, 240, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.loc = QtGui.QLineEdit(self.grpcuff)
        self.loc.setGeometry(QtCore.QRect(10,260 , 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loc.setFont(font)
        self.loc.setObjectName(_fromUtf8("loc"))
        self.loc.setToolTip("It takes integer value")
        self.bckfr = QtGui.QPushButton(self.grpcuff)
        self.bckfr.setGeometry(QtCore.QRect(500, 350, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setWeight(50)
        self.bckfr.setFont(font)
        self.bckfr.setObjectName(_fromUtf8("bckfr"))
        self.bckfr.setToolTip("Goes back to main page")
        self.label_30 = QtGui.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(10, 430, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.the = QtGui.QLineEdit(self.frame)
        self.the.setGeometry(QtCore.QRect(10,450 , 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.the.setFont(font)
        self.the.setObjectName(_fromUtf8("the"))
        self.the.setToolTip("It takes integer value")
        self.label_31 = QtGui.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(10, 500, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.mate = QtGui.QLineEdit(self.frame)
        self.mate.setGeometry(QtCore.QRect(10,520 , 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.mate.setFont(font)
        self.mate.setObjectName(_fromUtf8("mate"))
        self.mate.setToolTip("It takes integer value")
        self.label_32 = QtGui.QLabel(self.frame)
        self.label_32.setGeometry(QtCore.QRect(10, 570, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.std = QtGui.QLineEdit(self.frame)
        self.std.setGeometry(QtCore.QRect(10,590 , 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.std.setFont(font)
        self.std.setObjectName(_fromUtf8("std"))
        self.std.setToolTip("It takes integer value")


        self.Execute = QtGui.QPushButton(self.frame)
        self.Execute.setGeometry(QtCore.QRect(600, 700 , 98, 27))

        self.Execute.setObjectName(_fromUtf8("Execute"))
        self.Execute.setToolTip("Click to execute cuffquant")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CUFFQUANT", None))
        self.label_2.setText(_translate("MainWindow", "Transcripts", None))
        self.cmbgtf.setItemText(0, _translate("MainWindow", "", None))
        self.sing.setText(_translate("MainWindow", "", None))
        self.label_36.setText(_translate("MainWindow", "Add replicate", None))
        self.cmbfile.setItemText(0, _translate("MainWindow", "", None))
        self.fileu.setText(_translate("MainWindow", "", None))
        self.label_37.setText(_translate("MainWindow", "Use multi-read correct", None))
        self.mulyes.setText(_translate("MainWindow", "Yes", None))
        self.mulno.setText(_translate("MainWindow", "No", None))
#        self.label_3.setText(_translate("MainWindow", "Do you want to Perform Bias Correction", None))
#        self.cmbper.setItemText(0, _translate("MainWindow", "Yes", None))
#        self.cmbper.setItemText(1, _translate("MainWindow", "No", None))
        self.cmbseq.setItemText(0, _translate("MainWindow", "Locally cached", None))
        self.cmbseq.setItemText(1, _translate("MainWindow", "History", None))
        self.label_16.setText(_translate("MainWindow", "Reference sequence data", None))
        self.label_17.setText(_translate("MainWindow", "Using reference genome", None))
        self.cmbgen.setItemText(0, _translate("MainWindow", "", None))
        self.label_18.setText(_translate("MainWindow", "Using reference file", None))
        self.fil.setText(_translate("MainWindow", "", None))
        self.cmbfil.setItemText(0, _translate("MainWindow", "", None))
        self.label_19.setText(_translate("MainWindow", "Apply length correction", None))
        #self.cmbapp.setItemText(0, _translate("MainWindow", "Cufflinks effective length correction", None))
        self.cmbapp.setItemText(0, _translate("MainWindow", "Standrad length correction", None))
        self.cmbapp.setItemText(1, _translate("MainWindow", "No length correction at all(use raw counts)", None))
        self.label_20.setText(_translate("MainWindow", "Set Additional Parameters for single end reads", None))
        self.cmbset.setItemText(0, _translate("MainWindow", "Yes", None))
        self.cmbset.setItemText(1, _translate("MainWindow", "No", None))
        self.label_21.setText(_translate("MainWindow", "Average Fragment Length", None))
        self.label_22.setText(_translate("MainWindow", "Fragment Length Standard Deviation", None))
        self.label_27.setText(_translate("MainWindow", "Do you want to Set Advanced Cuffquant parameters? ", None))
        self.cmbpar.setItemText(0, _translate("MainWindow", "Yes", None))
        self.cmbpar.setItemText(1, _translate("MainWindow", "No", None))
        self.label_23.setText(_translate("MainWindow", "Library prep used for input reads", None))
        self.cmblib.setItemText(0, _translate("MainWindow", "ff-firststrand", None))
        self.cmblib.setItemText(1, _translate("MainWindow", "ff-secondstrand", None))
        self.cmblib.setItemText(2, _translate("MainWindow", "ff-unstranded", None))
        self.cmblib.setItemText(3, _translate("MainWindow", "fr-firststrand", None))
        self.cmblib.setItemText(4, _translate("MainWindow", "fr-secondstrand", None))
        self.cmblib.setItemText(5, _translate("MainWindow", "fr-unstranded", None))
        self.cmblib.setItemText(6, _translate("MainWindow", "transfrags", None))
        self.label_24.setText(_translate("MainWindow", "Mask File", None))
        self.mask.setText(_translate("MainWindow", "", None))
        self.cmbmask.setItemText(0, _translate("MainWindow", "", None))
        self.label_25.setText(_translate("MainWindow", "Max MLE iterations", None))
        self.label_26.setText(_translate("MainWindow", "Maximum number of fragments per locus", None))
        self.Execute.setText(_translate("MainWindow", "Execute", None))
        self.ok.setText(_translate("MainWindow", "Ok", None))
        self.bck.setText(_translate("MainWindow", "Ok", None))
        self.bckfr.setText(_translate("MainWindow", "Ok", None))
        self.label_30.setText(_translate("MainWindow", "Threads to align reads", None))
        self.label_31.setText(_translate("MainWindow", "Mean fragment length", None))
        self.label_32.setText(_translate("MainWindow", "Standard deviation for the distribution on fragment lengths.", None))
        #self.label_33.setText(_translate("MainWindow", "", None))
        #self.rep.setText(_translate("MainWindow", "Replicate", None))
#        self.addre.setText(_translate("MainWindow", "Insert Replicate", None))
#        self.label_6.setText(_translate("MainWindow", "Add replicate", None))
        self.cmbfilep.setItemText(0, _translate("MainWindow", "", None))
        self.filep.setText(_translate("MainWindow", "", None))
