# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bowtiegui.ui'
#
# Created: Tue Mar  1 14:46:40 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(870, 1500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 1500))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1500))
        MainWindow.setWhatsThis(_fromUtf8(""))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.centralWidget = QtGui.QWidget(MainWindow)
        layout = QtGui.QVBoxLayout(self.centralWidget)
        layout.addWidget(self.scrollArea)

        #self.scrollArea.setGeometry(QtCore.QRect(0, 0, 41, 111))
        #self.scrollArea.setWidgetResizable(True)
        #self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        #self.scrollAreaWidgetContents = QtGui.QWidget()
       # self.scrollArea.setGeometry(QtCore.QRect(230, 0, 841, 2481))
        self.scrollArea.setFrameShape(QtGui.QFrame.WinPanel)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setLineWidth(7)
        self.scrollArea.setWidgetResizable(False)

        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 812,600))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        layout = QtGui.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setGeometry(QtCore.QRect(30, 30, 760, 550))
        self.frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(10)

        #self.setStyleSheet('background-image: url("/home/amrata/PycharmProjects/bowtieuser/images/images/logn.jpg")')
        self.frame.setObjectName(_fromUtf8("frame"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

        #self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        #MainWindow.setCentralWidget(self.centralWidget)

        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 391, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.mul = QtGui.QPushButton(self.frame)
        self.mul.setGeometry(QtCore.QRect(10, 30, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mul.setIcon(icon)
        font.setWeight(50)
        self.mul.setFont(font)
        self.mul.setObjectName(_fromUtf8("mul"))
        self.mul.setToolTip("Pick a GTF file produced by cufflinks")
        self.cmbgtf = QtGui.QComboBox(self.frame)
        self.cmbgtf.setGeometry(QtCore.QRect(70, 30, 650, 27))
        self.cmbgtf.setObjectName(_fromUtf8("cmbgtf"))
        self.cmbgtf.setFont(font)
        self.cmbgtf.setToolTip("GTF file produced by cufflinks")
        ## self.addp.setGeometry(QtCore.QRect(10, 80, 230, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #font.setWeight(50)
        #self.addp.setFont(font)
        #self.addp.setObjectName(_fromUtf8("addp"))
        self.grpadd = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grpadd.setGeometry(QtCore.QRect(10, 10, 841, 700))
        self.grpadd.setTitle(_fromUtf8(""))
        self.grpadd.setObjectName(_fromUtf8("grpadd"))
        #self.frame_1 = QtGui.QFrame(self.grpadd)
        #self.frame_1.setGeometry(QtCore.QRect(00, 20, 750, 600))
        #self.frame_1.setFrameShape(QtGui.QFrame.StyledPanel)
        #self.frame_1.setLineWidth(14)
        #self.frame_1.setObjectName(_fromUtf8("frame_1"))

        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 391, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.add = QtGui.QPushButton(self.frame)
        self.add.setGeometry(QtCore.QRect(10,100, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        font.setWeight(50)
        self.add.setFont(font)
        self.add.setObjectName(_fromUtf8("add"))
        self.add.setToolTip("Pick a additional GTF file")
        self.cmbadd = QtGui.QComboBox(self.frame)
        self.cmbadd.setGeometry(QtCore.QRect(70, 100, 650, 27))
        self.cmbadd.setObjectName(_fromUtf8("cmbadd"))
        self.cmbadd.setFont(font)
        self.cmbadd.setToolTip("Additional GTF file produced by cufflinks")
        #self.addpu = QtGui.QPushButton(self.grpadd)
        #self.addpu.setGeometry(QtCore.QRect(10, 150, 230, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #font.setWeight(50)
        #self.addpu.setFont(font)
        #self.addpu.setObjectName(_fromUtf8("addpu"))
        #self.clos = QtGui.QPushButton(self.grpadd)
        #self.clos.setGeometry(QtCore.QRect(500, 150, 70, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #font.setWeight(50)
        #self.clos.setFont(font)
        #self.clos.setObjectName(_fromUtf8("clos"))
        #self.clos.setToolTip("Goes back to the main page")
        #self.grpaddg = QtGui.QGroupBox(self.grpadd)
        #self.grpaddg.setGeometry(QtCore.QRect(10, 120, 841, 150))
        #self.grpaddg.setTitle(_fromUtf8(""))
        #self.grpaddg.setObjectName(_fromUtf8("grpaddg"))
        #self.label_6 = QtGui.QLabel(self.grpaddg)
        ##self.label_6.setGeometry(QtCore.QRect(10, 10, 391, 17))
        #font = QtGui.QFont()
        #font.setBold(True)
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(12)
        #font.setWeight(75)
        #self.label_6.setFont(font)
        #self.label_6.setObjectName(_fromUtf8("label_6"))
        #self.sinp = QtGui.QPushButton(self.grpaddg)
        #self.sinp.setGeometry(QtCore.QRect(10, 30, 51, 27))
        #font = QtGui.QFont()
        #font.setFamily(_fromUtf8("Droid Serif"))
        #font.setPointSize(11)
        #icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/user/PycharmProjects/tophat/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        #self.sinp.setIcon(icon)
        #font.setWeight(50)
        #self.sinp.setFont(font)
        #self.sinp.setObjectName(_fromUtf8("sinp"))
        #self.sinp.setToolTip("")
        #self.cmbgtfil = QtGui.QComboBox(self.grpaddg)
        #self.cmbgtfil.setGeometry(QtCore.QRect(70, 30, 650, 27))
        #elf.cmbgtfil.setObjectName(_fromUtf8("cmbgtfi"))
        #self.cmbgtfil.addItem(_fromUtf8(""))
        #self.cmbgtfil.setFont(font)
        #self.cmbgtfil.setToolTip("")
        self.label_36 = QtGui.QLabel(self.frame)
        self.label_36.setGeometry(QtCore.QRect(10, 150, 391, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.cmbref = QtGui.QComboBox(self.frame)
        self.cmbref.setGeometry(QtCore.QRect(10, 170, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)

        self.cmbref.setFont(font)
        self.cmbref.setObjectName(_fromUtf8("cmbref"))
       # self.cmbref.addItem(_fromUtf8(""))
        self.cmbref.addItem(_fromUtf8(""))
        self.cmbref.addItem(_fromUtf8(""))
        self.cmbref.setToolTip(("Click Yes to use Reference annotation and No to provide default values"))
        self.grpref = QtGui.QGroupBox(self.frame)
        self.grpref.setGeometry(QtCore.QRect(10, 190, 841, 131))
        self.grpref.setTitle(_fromUtf8(""))
        self.grpref.setObjectName(_fromUtf8("grpref"))
        self.label_37 = QtGui.QLabel(self.grpref)
        self.label_37.setGeometry(QtCore.QRect(0, 30, 391, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(True)
        font.setPointSize(12)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.sin = QtGui.QPushButton(self.grpref)
        self.sin.setGeometry(QtCore.QRect(0, 50, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sin.setIcon(icon)
        font.setWeight(50)
        self.sin.setFont(font)
        self.sin.setObjectName(_fromUtf8("sin"))
        self.sin.setToolTip("Pick a GTF file")
        self.cmbgtfi = QtGui.QComboBox(self.grpref)
        self.cmbgtfi.setGeometry(QtCore.QRect(70, 50, 650, 27))
        self.cmbgtfi.setObjectName(_fromUtf8("cmbgtfi"))
        self.cmbgtfi.setFont(font)
        self.cmbgtfi.setToolTip("It displays GTF file")
        self.grpuse = QtGui.QGroupBox(self.frame)
        self.grpuse.setGeometry(QtCore.QRect(10, 210, 841, 131))
        self.grpuse.setTitle(_fromUtf8(""))
        self.grpuse.setObjectName(_fromUtf8("grpuse"))
        self.label_3 = QtGui.QLabel(self.grpuse)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 391, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setBold(True)
        font.setPointSize(12)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbseq = QtGui.QComboBox(self.grpuse)
        self.cmbseq.setGeometry(QtCore.QRect(0, 40, 721, 27))
        self.cmbseq.setObjectName(_fromUtf8("cmbseq"))
        self.cmbseq.addItem(_fromUtf8(""))
        self.cmbseq.addItem(_fromUtf8(""))
        self.cmbseq.setFont(font)

        self.grpseq = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.grpseq.setGeometry(QtCore.QRect(10, 10, 841, 300))
        self.grpseq.setTitle(_fromUtf8(""))
        self.grpseq.setObjectName(_fromUtf8("grpseq"))
        self.frame_2 = QtGui.QFrame(self.grpseq)
        self.frame_2.setGeometry(QtCore.QRect(00, 20, 750, 250))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(14)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))


        self.label_16 = QtGui.QLabel(self.grpseq)
        self.label_16.setGeometry(QtCore.QRect(0, 30, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.cmbsour = QtGui.QComboBox(self.grpseq)
        self.cmbsour.setGeometry(QtCore.QRect(0, 50, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cmbsour.setFont(font)
        self.cmbsour.setObjectName(_fromUtf8("cmbsour"))
        self.cmbsour.addItem(_fromUtf8(""))
        self.cmbsour.addItem(_fromUtf8(""))
        self.grplocal = QtGui.QGroupBox(self.grpseq)
        self.grplocal.setGeometry(QtCore.QRect(0, 80, 841, 131))
        self.grplocal.setTitle(_fromUtf8(""))
        self.grplocal.setObjectName(_fromUtf8("grplocal"))

        self.label_17 = QtGui.QLabel(self.grplocal)
        self.label_17.setGeometry(QtCore.QRect(0, 20, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.cmbgen= QtGui.QComboBox(self.grplocal)
        self.cmbgen.setGeometry(QtCore.QRect(0, 50, 721, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cmbgen.setFont(font)
        self.cmbgen.setObjectName(_fromUtf8("cmbgen"))
        self.cmbgen.addItem(_fromUtf8(""))
        self.grphis = QtGui.QGroupBox(self.grpseq)
        self.grphis.setGeometry(QtCore.QRect(0, 80, 841, 131))
        self.grphis.setTitle(_fromUtf8(""))
        self.grphis.setObjectName(_fromUtf8("grphis"))
        self.label_18 = QtGui.QLabel(self.grphis)
        self.label_18.setGeometry(QtCore.QRect(0, 30, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.file = QtGui.QPushButton(self.grphis)
        self.file.setGeometry(QtCore.QRect(0, 50, 51, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(11)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("/home/amrata/PycharmProjects/bowtieuser/images/index.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.file.setIcon(icon)
        font.setWeight(50)
        self.file.setFont(font)
        self.file.setObjectName(_fromUtf8("file"))
        self.cmbfile = QtGui.QComboBox(self.grphis)
        self.cmbfile.setGeometry(QtCore.QRect(70, 50, 650, 27))
        self.cmbfile.setObjectName(_fromUtf8("cmbfile"))
        self.cmbfile.addItem(_fromUtf8(""))
        self.cmbfile.setFont(font)
        self.bckf = QtGui.QPushButton(self.grpseq)
        self.bckf.setGeometry(QtCore.QRect(300,200 , 98, 27))

        self.bckf.setObjectName(_fromUtf8("bckf"))

        self.grpfra = QtGui.QGroupBox(self.frame)
        self.grpfra.setGeometry(QtCore.QRect(10, 200, 841, 200))
        self.grpfra.setTitle(_fromUtf8(""))
        self.grpfra.setObjectName(_fromUtf8("grpfra"))
        self.label_19 = QtGui.QLabel(self.grpfra)
        self.label_19.setGeometry(QtCore.QRect(0, 20, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.iso = QtGui.QLineEdit(self.grpfra)
        self.iso.setGeometry(QtCore.QRect(0,40 , 100, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.iso.setFont(font)
        self.iso.setObjectName(_fromUtf8("iso"))
        self.iso.setToolTip("It displays value")
        self.horizontalSlider = QtGui.QSlider(self.grpfra)
        self.horizontalSlider.setGeometry(QtCore.QRect(120, 40, 590, 29))
        self.horizontalSlider.setMaximum(10000)
        self.horizontalSlider.setMinimum(0)
        #self.horizontalSlider.setProperty("value", 0)
        #self.horizontalSlider.setProperty("value", 2)

        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.horizontalSlider.setToolTip("Move the slider")
        self.label_25 = QtGui.QLabel(self.grpfra)
        self.label_25.setGeometry(QtCore.QRect(0, 90, 771, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.max = QtGui.QLineEdit(self.grpfra)
        self.max.setGeometry(QtCore.QRect(0,110 , 720, 27))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Serif"))
        font.setPointSize(12)
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.max.setFont(font)
        self.max.setObjectName(_fromUtf8("max"))
        self.max.setToolTip("It takes integer value")


        self.Execute = QtGui.QPushButton(self.frame)
        self.Execute.setGeometry(QtCore.QRect(600,400 , 98, 27))

        self.Execute.setObjectName(_fromUtf8("Execute"))
        self.Execute.setToolTip("Click to execute cuffmerge")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CUFFMERGE", None))
        self.label_2.setText(_translate("MainWindow", "GTF file(s) produced by Cufflinks", None))
        self.cmbgtf.setItemText(0, _translate("MainWindow", "", None))
        self.cmbadd.setItemText(0, _translate("MainWindow", "", None))
        self.label_5.setText(_translate("MainWindow", "Additional GTF file(s) produced by Cufflinks", None))
        self.add.setText(_translate("MainWindow", "", None))
        self.mul.setText(_translate("MainWindow", "", None))
        self.label_36.setText(_translate("MainWindow", "Do you want to Use Reference Annotation", None))
        self.cmbref.setItemText(0, _translate("MainWindow", "Yes", None))
        self.cmbref.setItemText(1, _translate("MainWindow", "No", None))
        self.label_37.setText(_translate("MainWindow", "Reference Annotation", None))
        self.cmbgtfi.setItemText(0, _translate("MainWindow", "", None))
        self.sin.setText(_translate("MainWindow", "", None))
        #self.ok.setText(_translate("MainWindow", "Ok", None))
        self.label_3.setText(_translate("MainWindow", "Do you want to Use Sequence Data", None))
        self.cmbseq.setItemText(0, _translate("MainWindow", "Yes", None))
        self.cmbseq.setItemText(1, _translate("MainWindow", "No", None))
        self.label_16.setText(_translate("MainWindow", "Choose the source for the reference list ", None))
        self.cmbsour.setItemText(0, _translate("MainWindow", "Locally cached", None))
        self.cmbsour.setItemText(1, _translate("MainWindow", "History", None))
        #self.bck.setText(_translate("MainWindow", "Ok", None))
        self.label_17.setText(_translate("MainWindow", "Using reference genome", None))
        self.cmbgen.setItemText(0, _translate("MainWindow", "", None))
        self.label_18.setText(_translate("MainWindow", "Using reference file", None))
        self.file.setText(_translate("MainWindow", "", None))
        self.cmbfile.setItemText(0, _translate("MainWindow", "", None))
        self.label_19.setText(_translate("MainWindow", "Minimum isoform fraction", None))
        self.label_25.setText(_translate("MainWindow", "Threads to align reads", None))
        self.Execute.setText(_translate("MainWindow", "Execute", None))
        self.bckf.setText(_translate("MainWindow", "Ok", None))
#        self.addp.setText(_translate("MainWindow", "Additional GTF Inputs (Lists)", None))
#        self.addpu.setText(_translate("MainWindow", "Additional GTF Inputs (Lists)", None))
 #       self.label_6.setText(_translate("MainWindow", "Additional GTF file(s) produced by Cufflinks", None))
  #      self.cmbgtfil.setItemText(0, _translate("MainWindow", "", None))
   #     self.sinp.setText(_translate("MainWindow", "", None))
    #    self.clos.setText(_translate("MainWindow", "Close", None))
